lappend pragmaStatus0 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "calc_ma" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcB" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "est"}
lappend pragmaStatus2 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcB" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcB" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcB" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "sgn"}
lappend pragmaStatus5 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabx"}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabx"}
lappend pragmaStatus7 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabx"}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans"}
lappend pragmaStatus9 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_taby"}
lappend pragmaStatus10 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_taby"}
lappend pragmaStatus11 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_taby"}
lappend pragmaStatus12 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_1"}
lappend pragmaStatus13 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcC" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "est"}
lappend pragmaStatus14 {pragma "ARRAY_RESHAPE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcC" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "sgn"}
lappend pragmaStatus15 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcC" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcC" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAA" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus18 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAB" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAB' does not exist in any synthesis source file."}
lappend pragmaStatus19 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAB" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAB' does not exist in any synthesis source file."}
lappend pragmaStatus20 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcA" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcA' does not exist in any synthesis source file."}
lappend pragmaStatus21 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcA" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcA' does not exist in any synthesis source file."}
lappend pragmaStatus22 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcD" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus23 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcD" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus24 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcD" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "est"}
lappend pragmaStatus25 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcD" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "sgn"}
lappend pragmaStatus26 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabz"}
lappend pragmaStatus27 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabz"}
lappend pragmaStatus28 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabz"}
lappend pragmaStatus29 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_2"}
lappend pragmaStatus30 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabe"}
lappend pragmaStatus31 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabe"}
lappend pragmaStatus32 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabe"}
lappend pragmaStatus33 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_3"}
lappend pragmaStatus34 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAC" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAC' does not exist in any synthesis source file."}
lappend pragmaStatus35 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAC" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAC' does not exist in any synthesis source file."}
lappend pragmaStatus36 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAE" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAE' does not exist in any synthesis source file."}
lappend pragmaStatus37 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAE" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAE' does not exist in any synthesis source file."}
lappend pragmaStatus38 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcE" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus39 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcE" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus40 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabg"}
lappend pragmaStatus41 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabf"}
lappend pragmaStatus42 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabf"}
lappend pragmaStatus43 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabf"}
lappend pragmaStatus44 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_4"}
lappend pragmaStatus45 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabg"}
lappend pragmaStatus46 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabg"}
lappend pragmaStatus47 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabg"}
lappend pragmaStatus48 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_5"}
lappend pragmaStatus49 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabh"}
lappend pragmaStatus50 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabh"}
lappend pragmaStatus51 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabh"}
lappend pragmaStatus52 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_6"}
lappend pragmaStatus53 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAF" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAF' does not exist in any synthesis source file."}
lappend pragmaStatus54 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAF" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAF' does not exist in any synthesis source file."}
lappend pragmaStatus55 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAG" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAG' does not exist in any synthesis source file."}
lappend pragmaStatus56 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAG" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAG' does not exist in any synthesis source file."}
lappend pragmaStatus57 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAH" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAH' does not exist in any synthesis source file."}
lappend pragmaStatus58 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAH" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAH' does not exist in any synthesis source file."}
lappend pragmaStatus59 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcF" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus60 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcF" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus61 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcG" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus62 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcG" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus63 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcH" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcH' does not exist in any synthesis source file."}
lappend pragmaStatus64 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcH" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcH' does not exist in any synthesis source file."}
lappend pragmaStatus65 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabi"}
lappend pragmaStatus66 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabi"}
lappend pragmaStatus67 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabi"}
lappend pragmaStatus68 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_7"}
lappend pragmaStatus69 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabj"}
lappend pragmaStatus70 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabj"}
lappend pragmaStatus71 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabj"}
lappend pragmaStatus72 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_8"}
lappend pragmaStatus73 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAI" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAI' does not exist in any synthesis source file."}
lappend pragmaStatus74 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAI" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAI' does not exist in any synthesis source file."}
lappend pragmaStatus75 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAJ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAJ' does not exist in any synthesis source file."}
lappend pragmaStatus76 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAJ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAJ' does not exist in any synthesis source file."}
lappend pragmaStatus77 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabk"}
lappend pragmaStatus78 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabk"}
lappend pragmaStatus79 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabk"}
lappend pragmaStatus80 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_9"}
lappend pragmaStatus81 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabl"}
lappend pragmaStatus82 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabl"}
lappend pragmaStatus83 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabl"}
lappend pragmaStatus84 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabl"}
lappend pragmaStatus85 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_10"}
lappend pragmaStatus86 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabm"}
lappend pragmaStatus87 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabm"}
lappend pragmaStatus88 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabm"}
lappend pragmaStatus89 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_11"}
lappend pragmaStatus90 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAK" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAK' does not exist in any synthesis source file."}
lappend pragmaStatus91 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAK" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAK' does not exist in any synthesis source file."}
lappend pragmaStatus92 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAL" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAL' does not exist in any synthesis source file."}
lappend pragmaStatus93 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAL" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAL' does not exist in any synthesis source file."}
lappend pragmaStatus94 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAM" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAM' does not exist in any synthesis source file."}
lappend pragmaStatus95 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAM" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAM' does not exist in any synthesis source file."}
lappend pragmaStatus96 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcI" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcI' does not exist in any synthesis source file."}
lappend pragmaStatus97 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcI" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcI' does not exist in any synthesis source file."}
lappend pragmaStatus98 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcJ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcJ' does not exist in any synthesis source file."}
lappend pragmaStatus99 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcJ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcJ' does not exist in any synthesis source file."}
lappend pragmaStatus100 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcK" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcK' does not exist in any synthesis source file."}
lappend pragmaStatus101 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcK" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcK' does not exist in any synthesis source file."}
lappend pragmaStatus102 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcL" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcL' does not exist in any synthesis source file."}
lappend pragmaStatus103 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcL" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcL' does not exist in any synthesis source file."}
lappend pragmaStatus104 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcM" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcM' does not exist in any synthesis source file."}
lappend pragmaStatus105 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcM" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcM' does not exist in any synthesis source file."}
lappend pragmaStatus106 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabn"}
lappend pragmaStatus107 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabn"}
lappend pragmaStatus108 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_12"}
lappend pragmaStatus109 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabo"}
lappend pragmaStatus110 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabo"}
lappend pragmaStatus111 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabo"}
lappend pragmaStatus112 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_13"}
lappend pragmaStatus113 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabp"}
lappend pragmaStatus114 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabp"}
lappend pragmaStatus115 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabp"}
lappend pragmaStatus116 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_14"}
lappend pragmaStatus117 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Peta_tabq"}
lappend pragmaStatus118 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_tabq"}
lappend pragmaStatus119 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Eta_ans_15"}
lappend pragmaStatus120 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabn"}
lappend pragmaStatus121 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "Lam_tabq"}
lappend pragmaStatus122 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAN" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAN' does not exist in any synthesis source file."}
lappend pragmaStatus123 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAN" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAN' does not exist in any synthesis source file."}
lappend pragmaStatus124 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAO" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAO' does not exist in any synthesis source file."}
lappend pragmaStatus125 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAO" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAO' does not exist in any synthesis source file."}
lappend pragmaStatus126 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAP' does not exist in any synthesis source file."}
lappend pragmaStatus127 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAP' does not exist in any synthesis source file."}
lappend pragmaStatus128 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAQ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcAQ' does not exist in any synthesis source file."}
lappend pragmaStatus129 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAQ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcAQ' does not exist in any synthesis source file."}
lappend pragmaStatus130 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcN" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcN' does not exist in any synthesis source file."}
lappend pragmaStatus131 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcN" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcN' does not exist in any synthesis source file."}
lappend pragmaStatus132 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcO" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcO' does not exist in any synthesis source file."}
lappend pragmaStatus133 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcO" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcO' does not exist in any synthesis source file."}
lappend pragmaStatus134 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcP' does not exist in any synthesis source file."}
lappend pragmaStatus135 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcP' does not exist in any synthesis source file."}
lappend pragmaStatus136 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcQ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'mcalcQ' does not exist in any synthesis source file."}
lappend pragmaStatus137 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcQ" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'mcalcQ' does not exist in any synthesis source file."}
lappend pragmaStatus138 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "calc_n" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus139 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "test_ram" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'test_ram' does not exist in any synthesis source file."}
lappend pragmaStatus140 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "calc_n_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'calc_n_1' does not exist in any synthesis source file."}
lappend pragmaStatus141 {pragma "UNROLL" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "calc_n_1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'calc_n_1' does not exist in any synthesis source file."}
lappend pragmaStatus142 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf"}
lappend pragmaStatus143 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf1' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf1"}
lappend pragmaStatus144 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prLam_buf2"}
lappend pragmaStatus145 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf3' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf3"}
lappend pragmaStatus146 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prLam_buf4"}
lappend pragmaStatus147 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf5' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf5"}
lappend pragmaStatus148 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf6' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf6"}
lappend pragmaStatus149 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf7' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf7"}
lappend pragmaStatus150 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf8' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf8"}
lappend pragmaStatus151 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf9' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf9"}
lappend pragmaStatus152 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'RAM_T2P_BRAM' cannot be applied: Variable 'prLam_buf10' is not declared in 'HLSLdpcLogDecScaledMin'." variable "prLam_buf10"}
lappend pragmaStatus153 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "write_result" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus154 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "chk_parity_all" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'chk_parity_all' does not exist in any synthesis source file."}
lappend pragmaStatus155 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "write_result_23" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus156 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAA_23" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus157 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "write_result_12" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus158 {pragma "ARRAY_PARTITION" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "inxtab"}
lappend pragmaStatus159 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf6"}
lappend pragmaStatus160 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf"}
lappend pragmaStatus161 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf1"}
lappend pragmaStatus162 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf2"}
lappend pragmaStatus163 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf3"}
lappend pragmaStatus164 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf4"}
lappend pragmaStatus165 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf8"}
lappend pragmaStatus166 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf10"}
lappend pragmaStatus167 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA"}
lappend pragmaStatus168 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA1"}
lappend pragmaStatus169 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA2"}
lappend pragmaStatus170 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA3"}
lappend pragmaStatus171 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA4"}
lappend pragmaStatus172 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA5"}
lappend pragmaStatus173 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA6"}
lappend pragmaStatus174 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA7"}
lappend pragmaStatus175 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA9"}
lappend pragmaStatus176 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA10"}
lappend pragmaStatus177 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB"}
lappend pragmaStatus178 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB1"}
lappend pragmaStatus179 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB2"}
lappend pragmaStatus180 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB3"}
lappend pragmaStatus181 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB4"}
lappend pragmaStatus182 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB5"}
lappend pragmaStatus183 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB6"}
lappend pragmaStatus184 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB7"}
lappend pragmaStatus185 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB9"}
lappend pragmaStatus186 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB10"}
lappend pragmaStatus187 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf4a"}
lappend pragmaStatus188 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufAa"}
lappend pragmaStatus189 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA4a"}
lappend pragmaStatus190 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB1a"}
lappend pragmaStatus191 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB5a"}
lappend pragmaStatus192 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA2a"}
lappend pragmaStatus193 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA10a"}
lappend pragmaStatus194 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA6a"}
lappend pragmaStatus195 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB3a"}
lappend pragmaStatus196 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf10a"}
lappend pragmaStatus197 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB7a"}
lappend pragmaStatus198 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB9a"}
lappend pragmaStatus199 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf6a"}
lappend pragmaStatus200 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA4b"}
lappend pragmaStatus201 {pragma "PIPELINE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "mcalcAA_12" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus202 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_buf10b"}
lappend pragmaStatus203 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB1b"}
lappend pragmaStatus204 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB1c"}
lappend pragmaStatus205 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB5b"}
lappend pragmaStatus206 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB5c"}
lappend pragmaStatus207 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA10b"}
lappend pragmaStatus208 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA10c"}
lappend pragmaStatus209 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufAb"}
lappend pragmaStatus210 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufAc"}
lappend pragmaStatus211 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB3b"}
lappend pragmaStatus212 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufB3c"}
lappend pragmaStatus213 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA2b"}
lappend pragmaStatus214 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA2c"}
lappend pragmaStatus215 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA6b"}
lappend pragmaStatus216 {pragma "RESOURCE" source "C:/Users/dougo/LDPC_Decoder3U/HLSLdpcLogDecScaledMin.cpp" location "HLSLdpcLogDecScaledMin" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "prHat_bufA6c"}
