set_property PACKAGE_PIN AM20 [get_ports {adc0[0]}]
set_property PACKAGE_PIN AK22 [get_ports {adc0[1]}]
set_property PACKAGE_PIN AK23 [get_ports {adc0[2]}]
set_property PACKAGE_PIN AJ21 [get_ports {adc0[3]}]
set_property PACKAGE_PIN AK21 [get_ports {adc0[4]}]
set_property PACKAGE_PIN AK25 [get_ports {adc0[5]}]
set_property PACKAGE_PIN AL24 [get_ports {adc0[6]}]
set_property PACKAGE_PIN AL25 [get_ports {adc0[7]}]
set_property PACKAGE_PIN AL22 [get_ports {adc0[8]}]
set_property PACKAGE_PIN AL23 [get_ports {adc0[9]}]
set_property PACKAGE_PIN AJ20 [get_ports {adc0[10]}]
set_property PACKAGE_PIN AK20 [get_ports {adc0[11]}]
set_property PACKAGE_PIN AM24 [get_ports {adc0[12]}]
set_property PACKAGE_PIN AN24 [get_ports {adc0[13]}]
set_property PACKAGE_PIN AM22 [get_ports adc0_overflow]
set_property PACKAGE_PIN AN23 [get_ports adc01_powerDown]
set_property PACKAGE_PIN AJ23 [get_ports adc0Clock]

set_property PACKAGE_PIN AH9 [get_ports spiClk]
set_property PACKAGE_PIN AD9 [get_ports spiCSn]
set_property PACKAGE_PIN AE10 [get_ports spiDataIn]
set_property PACKAGE_PIN AH8 [get_ports spiDataOut]

set_property PACKAGE_PIN AH34 [get_ports dac_rst]
set_property PACKAGE_PIN AJ31 [get_ports dac_sdio]
set_property PACKAGE_PIN AJ30 [get_ports dac_sclk]

set_property PACKAGE_PIN AH29 [get_ports {dac0_d[0]}]
set_property PACKAGE_PIN AP33 [get_ports {dac0_d[1]}]
set_property PACKAGE_PIN AP31 [get_ports {dac0_d[2]}]
set_property PACKAGE_PIN AN33 [get_ports {dac0_d[3]}]
set_property PACKAGE_PIN AN31 [get_ports {dac0_d[4]}]
set_property PACKAGE_PIN AL33 [get_ports {dac0_d[5]}]
set_property PACKAGE_PIN AL32 [get_ports {dac0_d[6]}]
set_property PACKAGE_PIN AP34 [get_ports {dac0_d[7]}]
set_property PACKAGE_PIN AN34 [get_ports {dac0_d[8]}]
set_property PACKAGE_PIN AN32 [get_ports {dac0_d[9]}]
set_property PACKAGE_PIN AM34 [get_ports {dac0_d[10]}]
set_property PACKAGE_PIN AM32 [get_ports {dac0_d[11]}]
set_property PACKAGE_PIN AL34 [get_ports {dac0_d[12]}]
set_property PACKAGE_PIN AK33 [get_ports {dac0_d[13]}]
set_property PACKAGE_PIN AH32 [get_ports dac0_clk]
set_property PACKAGE_PIN AJ33 [get_ports dac0_nCs]

set_property PACKAGE_PIN AK27 [get_ports {dac1_d[0]}]
set_property PACKAGE_PIN AK26 [get_ports {dac1_d[1]}]
set_property PACKAGE_PIN AJ26 [get_ports {dac1_d[2]}]
set_property PACKAGE_PIN AH26 [get_ports {dac1_d[3]}]
set_property PACKAGE_PIN AL28 [get_ports {dac1_d[4]}]
set_property PACKAGE_PIN AL27 [get_ports {dac1_d[5]}]
set_property PACKAGE_PIN AK28 [get_ports {dac1_d[6]}]
set_property PACKAGE_PIN AJ28 [get_ports {dac1_d[7]}]
set_property PACKAGE_PIN AH28 [get_ports {dac1_d[8]}]
set_property PACKAGE_PIN AH27 [get_ports {dac1_d[9]}]
set_property PACKAGE_PIN AG26 [get_ports {dac1_d[10]}]
set_property PACKAGE_PIN AP29 [get_ports {dac1_d[11]}]
set_property PACKAGE_PIN AP28 [get_ports {dac1_d[12]}]
set_property PACKAGE_PIN AP26 [get_ports {dac1_d[13]}]
set_property PACKAGE_PIN AM27 [get_ports dac1_clk]
set_property PACKAGE_PIN AJ34 [get_ports dac1_nCs]

set_property PACKAGE_PIN AJ13 [get_ports ch0ClkOut]
set_property PACKAGE_PIN AK11 [get_ports ch0DataOut]
set_property PACKAGE_PIN AH12 [get_ports ch1ClkOut]
set_property PACKAGE_PIN AJ11 [get_ports ch1DataOut]

set_property PACKAGE_PIN AF20 [get_ports lockLed0n]
set_property PACKAGE_PIN AD20 [get_ports lockLed1n]

set_property PACKAGE_PIN AE8 [get_ports pll0_REF]
set_property PACKAGE_PIN AF10 [get_ports pll0_OUT1]
set_property PACKAGE_PIN AF8 [get_ports pll1_REF]
set_property PACKAGE_PIN AF9 [get_ports pll1_OUT1]

set_property PACKAGE_PIN AG9 [get_ports amAdcDataIn]
set_property PACKAGE_PIN AE11 [get_ports amAdcClk]
set_property PACKAGE_PIN AD11 [get_ports amAdcCSn]

set_property PACKAGE_PIN AD10 [get_ports amDacDataOut]
set_property PACKAGE_PIN AP9 [get_ports amDacClk]
set_property PACKAGE_PIN AN9 [get_ports amDacCSn]

set_property PACKAGE_PIN AL10 [get_ports switch0SpiClk]
set_property PACKAGE_PIN AL9 [get_ports switch0SpiDout]
set_property PACKAGE_PIN AP8 [get_ports switch0SpiCS0n]
set_property PACKAGE_PIN AK10 [get_ports switch0SpiCS1n]
set_property PACKAGE_PIN AK8 [get_ports switch1SpiClk]
set_property PACKAGE_PIN AJ8 [get_ports switch1SpiDout]
set_property PACKAGE_PIN AJ9 [get_ports switch1SpiCS0n]
set_property PACKAGE_PIN AM9 [get_ports switch1SpiCS1n]

set_property IOSTANDARD LVCMOS18 [get_ports {adc0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports adc0_overflow]
set_property IOSTANDARD LVCMOS18 [get_ports adc01_powerDown]
set_property DRIVE 12 [get_ports adc01_powerDown]
set_property SLEW SLOW [get_ports adc01_powerDown]
set_property IOSTANDARD LVCMOS18 [get_ports adc0Clock]

set_property IOSTANDARD LVCMOS33 [get_ports spiClk]
set_property IOSTANDARD LVCMOS33 [get_ports spiCSn]
set_property IOSTANDARD LVCMOS33 [get_ports spiDataIn]
set_property IOSTANDARD LVCMOS33 [get_ports spiDataOut]
set_property DRIVE 12 [get_ports spiDataOut]
set_property SLEW SLOW [get_ports spiDataOut]

set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[0]}]
set_property DRIVE 12 [get_ports {dac0_d[0]}]
set_property SLEW FAST [get_ports {dac0_d[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[10]}]
set_property DRIVE 12 [get_ports {dac0_d[10]}]
set_property SLEW FAST [get_ports {dac0_d[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[11]}]
set_property DRIVE 12 [get_ports {dac0_d[11]}]
set_property SLEW FAST [get_ports {dac0_d[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[12]}]
set_property DRIVE 12 [get_ports {dac0_d[12]}]
set_property SLEW FAST [get_ports {dac0_d[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[13]}]
set_property DRIVE 12 [get_ports {dac0_d[13]}]
set_property SLEW FAST [get_ports {dac0_d[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[1]}]
set_property DRIVE 12 [get_ports {dac0_d[1]}]
set_property SLEW FAST [get_ports {dac0_d[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[2]}]
set_property DRIVE 12 [get_ports {dac0_d[2]}]
set_property SLEW FAST [get_ports {dac0_d[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[3]}]
set_property DRIVE 12 [get_ports {dac0_d[3]}]
set_property SLEW FAST [get_ports {dac0_d[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[4]}]
set_property DRIVE 12 [get_ports {dac0_d[4]}]
set_property SLEW FAST [get_ports {dac0_d[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[5]}]
set_property DRIVE 12 [get_ports {dac0_d[5]}]
set_property SLEW FAST [get_ports {dac0_d[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[6]}]
set_property DRIVE 12 [get_ports {dac0_d[6]}]
set_property SLEW FAST [get_ports {dac0_d[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[7]}]
set_property DRIVE 12 [get_ports {dac0_d[7]}]
set_property SLEW FAST [get_ports {dac0_d[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[8]}]
set_property DRIVE 12 [get_ports {dac0_d[8]}]
set_property SLEW FAST [get_ports {dac0_d[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[9]}]
set_property DRIVE 12 [get_ports {dac0_d[9]}]
set_property SLEW FAST [get_ports {dac0_d[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[0]}]
set_property DRIVE 12 [get_ports {dac1_d[0]}]
set_property SLEW FAST [get_ports {dac1_d[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[10]}]
set_property DRIVE 12 [get_ports {dac1_d[10]}]
set_property SLEW FAST [get_ports {dac1_d[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[11]}]
set_property DRIVE 12 [get_ports {dac1_d[11]}]
set_property SLEW FAST [get_ports {dac1_d[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[12]}]
set_property DRIVE 12 [get_ports {dac1_d[12]}]
set_property SLEW FAST [get_ports {dac1_d[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[13]}]
set_property DRIVE 12 [get_ports {dac1_d[13]}]
set_property SLEW FAST [get_ports {dac1_d[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[1]}]
set_property DRIVE 12 [get_ports {dac1_d[1]}]
set_property SLEW FAST [get_ports {dac1_d[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[2]}]
set_property DRIVE 12 [get_ports {dac1_d[2]}]
set_property SLEW FAST [get_ports {dac1_d[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[3]}]
set_property DRIVE 12 [get_ports {dac1_d[3]}]
set_property SLEW FAST [get_ports {dac1_d[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[4]}]
set_property DRIVE 12 [get_ports {dac1_d[4]}]
set_property SLEW FAST [get_ports {dac1_d[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[5]}]
set_property DRIVE 12 [get_ports {dac1_d[5]}]
set_property SLEW FAST [get_ports {dac1_d[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[6]}]
set_property DRIVE 12 [get_ports {dac1_d[6]}]
set_property SLEW FAST [get_ports {dac1_d[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[7]}]
set_property DRIVE 12 [get_ports {dac1_d[7]}]
set_property SLEW FAST [get_ports {dac1_d[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[8]}]
set_property DRIVE 12 [get_ports {dac1_d[8]}]
set_property SLEW FAST [get_ports {dac1_d[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[9]}]
set_property DRIVE 12 [get_ports {dac1_d[9]}]
set_property SLEW FAST [get_ports {dac1_d[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports dac0_clk]
set_property DRIVE 12 [get_ports dac0_clk]
set_property SLEW FAST [get_ports dac0_clk]
set_property IOSTANDARD LVCMOS18 [get_ports dac0_nCs]
set_property DRIVE 12 [get_ports dac0_nCs]
set_property SLEW SLOW [get_ports dac0_nCs]
set_property IOSTANDARD LVCMOS18 [get_ports dac1_clk]
set_property DRIVE 12 [get_ports dac1_clk]
set_property SLEW FAST [get_ports dac1_clk]
set_property IOSTANDARD LVCMOS18 [get_ports dac1_nCs]
set_property DRIVE 12 [get_ports dac1_nCs]
set_property SLEW SLOW [get_ports dac1_nCs]
set_property IOSTANDARD LVCMOS18 [get_ports dac_rst]
set_property DRIVE 12 [get_ports dac_rst]
set_property SLEW SLOW [get_ports dac_rst]
set_property IOSTANDARD LVCMOS18 [get_ports dac_sclk]
set_property DRIVE 12 [get_ports dac_sclk]
set_property SLEW SLOW [get_ports dac_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports dac_sdio]
set_property DRIVE 12 [get_ports dac_sdio]
set_property SLEW SLOW [get_ports dac_sdio]

set_property IOSTANDARD LVCMOS33 [get_ports ch0ClkOut]
set_property DRIVE 12 [get_ports ch0ClkOut]
set_property SLEW SLOW [get_ports ch0ClkOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch0DataOut]
set_property DRIVE 12 [get_ports ch0DataOut]
set_property SLEW SLOW [get_ports ch0DataOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch1ClkOut]
set_property DRIVE 12 [get_ports ch1ClkOut]
set_property SLEW SLOW [get_ports ch1ClkOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch1DataOut]
set_property DRIVE 12 [get_ports ch1DataOut]
set_property SLEW SLOW [get_ports ch1DataOut]

set_property IOSTANDARD LVCMOS18 [get_ports lockLed0n]
set_property DRIVE 12 [get_ports lockLed0n]
set_property SLEW SLOW [get_ports lockLed0n]
set_property IOSTANDARD LVCMOS18 [get_ports lockLed1n]
set_property DRIVE 12 [get_ports lockLed1n]
set_property SLEW SLOW [get_ports lockLed1n]

set_property IOSTANDARD LVCMOS33 [get_ports pll0_REF]
set_property DRIVE 12 [get_ports pll0_REF]
set_property SLEW FAST [get_ports pll0_REF]
set_property IOSTANDARD LVCMOS33 [get_ports pll0_OUT1]
set_property IOSTANDARD LVCMOS33 [get_ports pll1_REF]
set_property DRIVE 12 [get_ports pll1_REF]
set_property SLEW FAST [get_ports pll1_REF]
set_property IOSTANDARD LVCMOS33 [get_ports pll1_OUT1]

set_property IOSTANDARD LVCMOS33 [get_ports amAdcDataIn]
set_property IOSTANDARD LVCMOS33 [get_ports amAdcClk]
set_property DRIVE 12 [get_ports amAdcClk]
set_property SLEW SLOW [get_ports amAdcClk]
set_property IOSTANDARD LVCMOS33 [get_ports amAdcCSn]
set_property DRIVE 12 [get_ports amAdcCSn]
set_property SLEW SLOW [get_ports amAdcCSn]

set_property IOSTANDARD LVCMOS33 [get_ports amDacDataOut]
set_property DRIVE 12 [get_ports amDacDataOut]
set_property SLEW SLOW [get_ports amDacDataOut]
set_property IOSTANDARD LVCMOS33 [get_ports amDacClk]
set_property DRIVE 12 [get_ports amDacClk]
set_property SLEW SLOW [get_ports amDacClk]
set_property IOSTANDARD LVCMOS33 [get_ports amDacCSn]
set_property DRIVE 12 [get_ports amDacCSn]
set_property SLEW SLOW [get_ports amDacCSn]

set_property IOSTANDARD LVCMOS33 [get_ports switch0SpiClk]
set_property DRIVE 12 [get_ports switch0SpiClk]
set_property SLEW SLOW [get_ports switch0SpiClk]
set_property IOSTANDARD LVCMOS33 [get_ports switch0SpiDout]
set_property DRIVE 12 [get_ports switch0SpiDout]
set_property SLEW SLOW [get_ports switch0SpiDout]
set_property IOSTANDARD LVCMOS33 [get_ports switch0SpiCS0n]
set_property DRIVE 12 [get_ports switch0SpiCS0n]
set_property SLEW SLOW [get_ports switch0SpiCS0n]
set_property IOSTANDARD LVCMOS33 [get_ports switch0SpiCS1n]
set_property DRIVE 12 [get_ports switch0SpiCS1n]
set_property SLEW SLOW [get_ports switch0SpiCS1n]
set_property IOSTANDARD LVCMOS33 [get_ports switch1SpiClk]
set_property DRIVE 12 [get_ports switch1SpiClk]
set_property SLEW SLOW [get_ports switch1SpiClk]
set_property IOSTANDARD LVCMOS33 [get_ports switch1SpiDout]
set_property DRIVE 12 [get_ports switch1SpiDout]
set_property SLEW SLOW [get_ports switch1SpiDout]
set_property IOSTANDARD LVCMOS33 [get_ports switch1SpiCS0n]
set_property DRIVE 12 [get_ports switch1SpiCS0n]
set_property SLEW SLOW [get_ports switch1SpiCS0n]
set_property IOSTANDARD LVCMOS33 [get_ports switch1SpiCS1n]
set_property DRIVE 12 [get_ports switch1SpiCS1n]
set_property SLEW SLOW [get_ports switch1SpiCS1n]













