# set_property PACKAGE_PIN C16 [get_ports ADC_Sync]
# set_property PACKAGE_PIN B16 [get_ports ADC_SDIO]
# set_property PACKAGE_PIN A18 [get_ports ADC_SClk]
set_property PACKAGE_PIN A17 [get_ports adc01_powerDown]
# set_property PACKAGE_PIN B17 [get_ports ADC_OE_n]
# set_property PACKAGE_PIN A19 [get_ports ADC_CS_n]

set_property PACKAGE_PIN E18 [get_ports adc0Clk]
# On Rev2 change to E18
set_property PACKAGE_PIN D15 [get_ports adc0_overflow]
set_property PACKAGE_PIN D16 [get_ports {adc0[13]}]
set_property PACKAGE_PIN H16 [get_ports {adc0[12]}]
set_property PACKAGE_PIN G16 [get_ports {adc0[11]}]
set_property PACKAGE_PIN G15 [get_ports {adc0[10]}]
set_property PACKAGE_PIN F15 [get_ports {adc0[9]}]
set_property PACKAGE_PIN J15 [get_ports {adc0[8]}]
set_property PACKAGE_PIN J16 [get_ports {adc0[7]}]
set_property PACKAGE_PIN E15 [get_ports {adc0[6]}]
set_property PACKAGE_PIN E16 [get_ports {adc0[5]}]
set_property PACKAGE_PIN G17 [get_ports {adc0[4]}]
set_property PACKAGE_PIN F18 [get_ports {adc0[3]}]
set_property PACKAGE_PIN F17 [get_ports {adc0[2]}]
set_property PACKAGE_PIN E17 [get_ports {adc0[1]}]
set_property PACKAGE_PIN D18 [get_ports {adc0[0]}]
# On Rev2 change to D18

set_property PACKAGE_PIN F10 [get_ports dac_sclk]
set_property PACKAGE_PIN E10 [get_ports dac_sdio]
set_property PACKAGE_PIN A8 [get_ports dac_rst]
set_property PACKAGE_PIN C9 [get_ports dac0_nCs]
set_property PACKAGE_PIN D8 [get_ports dac0_clk]
set_property PACKAGE_PIN H9 [get_ports {dac0_d[13]}]
set_property PACKAGE_PIN H8 [get_ports {dac0_d[12]}]
set_property PACKAGE_PIN G10 [get_ports {dac0_d[11]}]
set_property PACKAGE_PIN G9 [get_ports {dac0_d[10]}]
set_property PACKAGE_PIN J13 [get_ports {dac0_d[9]}]
set_property PACKAGE_PIN H13 [get_ports {dac0_d[8]}]
set_property PACKAGE_PIN J11 [get_ports {dac0_d[7]}]
set_property PACKAGE_PIN J10 [get_ports {dac0_d[6]}]
set_property PACKAGE_PIN H14 [get_ports {dac0_d[5]}]
set_property PACKAGE_PIN G14 [get_ports {dac0_d[4]}]
set_property PACKAGE_PIN H12 [get_ports {dac0_d[3]}]
set_property PACKAGE_PIN H11 [get_ports {dac0_d[2]}]
set_property PACKAGE_PIN F9 [get_ports {dac0_d[1]}]
set_property PACKAGE_PIN F8 [get_ports {dac0_d[0]}]
set_property PACKAGE_PIN A13 [get_ports dac1_clk]
set_property PACKAGE_PIN B9 [get_ports dac1_nCs]
set_property PACKAGE_PIN F12 [get_ports {dac1_d[13]}]
set_property PACKAGE_PIN D14 [get_ports {dac1_d[12]}]
set_property PACKAGE_PIN D13 [get_ports {dac1_d[11]}]
set_property PACKAGE_PIN E13 [get_ports {dac1_d[10]}]
set_property PACKAGE_PIN E12 [get_ports {dac1_d[9]}]
set_property PACKAGE_PIN C14 [get_ports {dac1_d[8]}]
set_property PACKAGE_PIN C13 [get_ports {dac1_d[7]}]
set_property PACKAGE_PIN B12 [get_ports {dac1_d[6]}]
set_property PACKAGE_PIN B11 [get_ports {dac1_d[5]}]
set_property PACKAGE_PIN B14 [get_ports {dac1_d[4]}]
set_property PACKAGE_PIN A14 [get_ports {dac1_d[3]}]
set_property PACKAGE_PIN B10 [get_ports {dac1_d[2]}]
set_property PACKAGE_PIN A10 [get_ports {dac1_d[1]}]
set_property PACKAGE_PIN B15 [get_ports {dac1_d[0]}]

set_property PACKAGE_PIN AF25 [get_ports DQMOut]
set_property PACKAGE_PIN AD26 [get_ports sdiOut]

set_property PACKAGE_PIN AE21 [get_ports ch0ClkOut]
set_property PACKAGE_PIN AD21 [get_ports ch0DataOut]

set_property PACKAGE_PIN Y21 [get_ports ch1ClkOut]
set_property PACKAGE_PIN AD23 [get_ports ch1DataOut]

set_property PACKAGE_PIN AD24 [get_ports ch2ClkOut]
set_property PACKAGE_PIN AB22 [get_ports ch2DataOut]

set_property PACKAGE_PIN AC24 [get_ports ch3ClkOut]
set_property PACKAGE_PIN AA22 [get_ports ch3DataOut]

set_property PACKAGE_PIN Y22 [get_ports pll0_OUT1]
# On Rev2 change to Y22
set_property PACKAGE_PIN Y23 [get_ports pll1_OUT1]
# On Rev2 change to Y23
set_property PACKAGE_PIN Y25 [get_ports pll0_REF]
set_property PACKAGE_PIN AA23 [get_ports pll1_REF]

set_property PACKAGE_PIN AB25 [get_ports spiCSn]
set_property PACKAGE_PIN W24 [get_ports spiDataOut]
set_property PACKAGE_PIN W23 [get_ports spiDataIn]
set_property PACKAGE_PIN AC23 [get_ports spiClk]
# On Rev2 change to AC23

set_property PACKAGE_PIN C23 [get_ports spiFlashCSn]
set_property PACKAGE_PIN B24 [get_ports spiFlashMOSI]
set_property PACKAGE_PIN A25 [get_ports spiFlashMISO]

set_property PACKAGE_PIN V22 [get_ports amAdcClk]
set_property PACKAGE_PIN U21 [get_ports amAdcDataIn]
set_property PACKAGE_PIN U22 [get_ports amAdcCSn]

set_property PACKAGE_PIN AF22 [get_ports amDacClk]
set_property PACKAGE_PIN AE22 [get_ports amDacCSn]
set_property PACKAGE_PIN Y20 [get_ports amDacDataOut]

set_property PACKAGE_PIN AD5 [get_ports {bsAdc[13]}]
set_property PACKAGE_PIN V1 [get_ports {bsAdc[12]}]
set_property PACKAGE_PIN AB1 [get_ports {bsAdc[11]}]
set_property PACKAGE_PIN V2 [get_ports {bsAdc[10]}]
set_property PACKAGE_PIN Y6 [get_ports {bsAdc[9]}]
set_property PACKAGE_PIN Y2 [get_ports {bsAdc[8]}]
set_property PACKAGE_PIN AA5 [get_ports {bsAdc[7]}]
set_property PACKAGE_PIN AC4 [get_ports {bsAdc[6]}]
set_property PACKAGE_PIN AC6 [get_ports {bsAdc[5]}]
set_property PACKAGE_PIN AB6 [get_ports {bsAdc[4]}]
set_property PACKAGE_PIN AB5 [get_ports {bsAdc[3]}]
set_property PACKAGE_PIN Y5 [get_ports {bsAdc[2]}]
set_property PACKAGE_PIN AC3 [get_ports {bsAdc[1]}]
set_property PACKAGE_PIN Y3 [get_ports {bsAdc[0]}]
set_property PACKAGE_PIN AD6 [get_ports bsAdc_overflow]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {bsAdc[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports bsAdc_overflow]
set_property PACKAGE_PIN W3 [get_ports bsAdc_powerDown]
set_property IOSTANDARD LVCMOS18 [get_ports bsAdc_powerDown]

set_property PACKAGE_PIN U2 [get_ports bsHighImpedance]
set_property IOSTANDARD LVCMOS18 [get_ports bsHighImpedance]
set_property PACKAGE_PIN AD1 [get_ports bsSingleEnded]
set_property IOSTANDARD LVCMOS18 [get_ports bsSingleEnded]

set_property PACKAGE_PIN AE3 [get_ports bsDacSELn]
set_property PACKAGE_PIN AE2 [get_ports bsDacSCLK]
set_property PACKAGE_PIN AE6 [get_ports bsDacMOSI]
set_property IOSTANDARD LVCMOS18 [get_ports bsDacSELn]
set_property IOSTANDARD LVCMOS18 [get_ports bsDacSCLK]
set_property IOSTANDARD LVCMOS18 [get_ports bsDacMOSI]

# set_property PACKAGE_PIN AA3 [get_ports BS_Clk]
# set_property PACKAGE_PIN AF5 [get_ports BS_I2C_SCl]
# set_property PACKAGE_PIN AF4 [get_ports BS_I2C_SDa]

# set_property PACKAGE_PIN H17 [get_ports MonClk]
# set_property PACKAGE_PIN F19 [get_ports MonOvf]
# set_property PACKAGE_PIN E20 [get_ports {MonData[13]}]
# set_property PACKAGE_PIN H19 [get_ports {MonData[12]}]
# set_property PACKAGE_PIN G20 [get_ports {MonData[11]}]
# set_property PACKAGE_PIN K20 [get_ports {MonData[10]}]
# set_property PACKAGE_PIN J20 [get_ports {MonData[9]}]
# set_property PACKAGE_PIN J18 [get_ports {MonData[8]}]
# set_property PACKAGE_PIN J19 [get_ports {MonData[7]}]
# set_property PACKAGE_PIN L19 [get_ports {MonData[6]}]
# set_property PACKAGE_PIN L20 [get_ports {MonData[5]}]
# set_property PACKAGE_PIN K16 [get_ports {MonData[4]}]
# set_property PACKAGE_PIN K17 [get_ports {MonData[3]}]
# set_property PACKAGE_PIN M17 [get_ports {MonData[2]}]
# set_property PACKAGE_PIN L18 [get_ports {MonData[1]}]
# set_property PACKAGE_PIN L17 [get_ports {MonData[0]}]

set_property PACKAGE_PIN AB21 [get_ports lockLed0n]
set_property PACKAGE_PIN AC21 [get_ports lockLed1n]

set_property PACKAGE_PIN W21 [get_ports {video1OutSelect[1]}]
set_property PACKAGE_PIN V21 [get_ports {video1OutSelect[0]}]
set_property PACKAGE_PIN W26 [get_ports {video0OutSelect[1]}]
set_property PACKAGE_PIN W25 [get_ports {video0OutSelect[0]}]

set_property PACKAGE_PIN U26 [get_ports {video1InSelect[1]}]
set_property PACKAGE_PIN V24 [get_ports {video1InSelect[0]}]
set_property PACKAGE_PIN V23 [get_ports {video0InSelect[1]}]
set_property PACKAGE_PIN U25 [get_ports {video0InSelect[0]}]

# set_property PACKAGE_PIN AB22 [get_ports {TtlOut[3]}]
# set_property PACKAGE_PIN AD24 [get_ports {TtlOut[2]}]
# set_property PACKAGE_PIN AD23 [get_ports {TtlOut[1]}]
# set_property PACKAGE_PIN Y21 [get_ports {TtlOut[0]}]

# set_property PACKAGE_PIN AE23 [get_ports {VidSel[2]}]
# set_property PACKAGE_PIN AF23 [get_ports {VidSel[1]}]
# set_property PACKAGE_PIN AD25 [get_ports {VidSel[0]}]

# set_property PACKAGE_PIN V19 [get_ports FPGA_ID1]
# set_property PULLUP true [get_ports FPGA_ID1]
# set_property PACKAGE_PIN V26 [get_ports FPGA_ID0]
# set_property PULLUP true [get_ports FPGA_ID0]

# set_property PACKAGE_PIN AB16 [get_ports NextChClkIn_p]
# set_property PACKAGE_PIN AA17 [get_ports NextChClkOut_p]
# set_property PACKAGE_PIN AB14 [get_ports NextChDataIn0_p]
# set_property PACKAGE_PIN Y15 [get_ports NextChDataIn1_p]
# set_property PACKAGE_PIN AA14 [get_ports NextChDataOut0_p]
# set_property PACKAGE_PIN AC14 [get_ports NextChDataOut1_p]
# set_property PACKAGE_PIN AC18 [get_ports PrevChClkIn_p]
# set_property PACKAGE_PIN AB17 [get_ports PrevChClkOut_p]
# set_property PACKAGE_PIN AA19 [get_ports PrevChDataIn0_p]
# set_property PACKAGE_PIN AD20 [get_ports PrevChDataIn1_p]
# set_property PACKAGE_PIN Y17 [get_ports PrevChDataOut0_p]
# set_property PACKAGE_PIN AB19 [get_ports PrevChDataOut1_p]


set_property IOSTANDARD LVCMOS18 [get_ports adc0Clk]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[0]}]
set_property DRIVE 12 [get_ports {dac0_d[0]}]
set_property SLEW FAST [get_ports {dac0_d[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[10]}]
set_property DRIVE 12 [get_ports {dac0_d[10]}]
set_property SLEW FAST [get_ports {dac0_d[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[11]}]
set_property DRIVE 12 [get_ports {dac0_d[11]}]
set_property SLEW FAST [get_ports {dac0_d[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[12]}]
set_property DRIVE 12 [get_ports {dac0_d[12]}]
set_property SLEW FAST [get_ports {dac0_d[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[13]}]
set_property DRIVE 12 [get_ports {dac0_d[13]}]
set_property SLEW FAST [get_ports {dac0_d[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[1]}]
set_property DRIVE 12 [get_ports {dac0_d[1]}]
set_property SLEW FAST [get_ports {dac0_d[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[2]}]
set_property DRIVE 12 [get_ports {dac0_d[2]}]
set_property SLEW FAST [get_ports {dac0_d[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[3]}]
set_property DRIVE 12 [get_ports {dac0_d[3]}]
set_property SLEW FAST [get_ports {dac0_d[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[4]}]
set_property DRIVE 12 [get_ports {dac0_d[4]}]
set_property SLEW FAST [get_ports {dac0_d[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[5]}]
set_property DRIVE 12 [get_ports {dac0_d[5]}]
set_property SLEW FAST [get_ports {dac0_d[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[6]}]
set_property DRIVE 12 [get_ports {dac0_d[6]}]
set_property SLEW FAST [get_ports {dac0_d[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[7]}]
set_property DRIVE 12 [get_ports {dac0_d[7]}]
set_property SLEW FAST [get_ports {dac0_d[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[8]}]
set_property DRIVE 12 [get_ports {dac0_d[8]}]
set_property SLEW FAST [get_ports {dac0_d[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac0_d[9]}]
set_property DRIVE 12 [get_ports {dac0_d[9]}]
set_property SLEW FAST [get_ports {dac0_d[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[0]}]
set_property DRIVE 12 [get_ports {dac1_d[0]}]
set_property SLEW FAST [get_ports {dac1_d[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[10]}]
set_property DRIVE 12 [get_ports {dac1_d[10]}]
set_property SLEW FAST [get_ports {dac1_d[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[11]}]
set_property DRIVE 12 [get_ports {dac1_d[11]}]
set_property SLEW FAST [get_ports {dac1_d[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[12]}]
set_property DRIVE 12 [get_ports {dac1_d[12]}]
set_property SLEW FAST [get_ports {dac1_d[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[13]}]
set_property DRIVE 12 [get_ports {dac1_d[13]}]
set_property SLEW FAST [get_ports {dac1_d[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[1]}]
set_property DRIVE 12 [get_ports {dac1_d[1]}]
set_property SLEW FAST [get_ports {dac1_d[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[2]}]
set_property DRIVE 12 [get_ports {dac1_d[2]}]
set_property SLEW FAST [get_ports {dac1_d[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[3]}]
set_property DRIVE 12 [get_ports {dac1_d[3]}]
set_property SLEW FAST [get_ports {dac1_d[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[4]}]
set_property DRIVE 12 [get_ports {dac1_d[4]}]
set_property SLEW FAST [get_ports {dac1_d[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[5]}]
set_property DRIVE 12 [get_ports {dac1_d[5]}]
set_property SLEW FAST [get_ports {dac1_d[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[6]}]
set_property DRIVE 12 [get_ports {dac1_d[6]}]
set_property SLEW FAST [get_ports {dac1_d[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[7]}]
set_property DRIVE 12 [get_ports {dac1_d[7]}]
set_property SLEW FAST [get_ports {dac1_d[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[8]}]
set_property DRIVE 12 [get_ports {dac1_d[8]}]
set_property SLEW FAST [get_ports {dac1_d[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dac1_d[9]}]
set_property DRIVE 12 [get_ports {dac1_d[9]}]
set_property SLEW FAST [get_ports {dac1_d[9]}]

set_property IOSTANDARD LVCMOS18 [get_ports adc01_powerDown]
set_property DRIVE 12 [get_ports adc01_powerDown]
set_property SLEW SLOW [get_ports adc01_powerDown]
set_property IOSTANDARD LVCMOS18 [get_ports adc0_overflow]
set_property IOSTANDARD LVCMOS18 [get_ports dac0_clk]
set_property DRIVE 12 [get_ports dac0_clk]
set_property SLEW FAST [get_ports dac0_clk]
set_property IOSTANDARD LVCMOS18 [get_ports dac0_nCs]
set_property DRIVE 12 [get_ports dac0_nCs]
set_property SLEW SLOW [get_ports dac0_nCs]
set_property IOSTANDARD LVCMOS18 [get_ports dac1_clk]
set_property DRIVE 12 [get_ports dac1_clk]
set_property SLEW FAST [get_ports dac1_clk]
set_property IOSTANDARD LVCMOS18 [get_ports dac1_nCs]
set_property DRIVE 12 [get_ports dac1_nCs]
set_property SLEW SLOW [get_ports dac1_nCs]
set_property IOSTANDARD LVCMOS18 [get_ports dac_rst]
set_property DRIVE 12 [get_ports dac_rst]
set_property SLEW SLOW [get_ports dac_rst]
set_property IOSTANDARD LVCMOS18 [get_ports dac_sclk]
set_property DRIVE 12 [get_ports dac_sclk]
set_property SLEW SLOW [get_ports dac_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports dac_sdio]
set_property DRIVE 12 [get_ports dac_sdio]
set_property SLEW SLOW [get_ports dac_sdio]

set_property IOSTANDARD LVCMOS33 [get_ports ch1DataOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch0ClkOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch1ClkOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch0DataOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch3DataOut]
set_property DRIVE 12 [get_ports ch1DataOut]
set_property SLEW SLOW [get_ports ch1DataOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch2ClkOut]
set_property DRIVE 12 [get_ports ch0ClkOut]
set_property SLEW SLOW [get_ports ch0ClkOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch3ClkOut]
set_property DRIVE 12 [get_ports ch1ClkOut]
set_property SLEW SLOW [get_ports ch1ClkOut]
set_property IOSTANDARD LVCMOS33 [get_ports ch2DataOut]
set_property DRIVE 12 [get_ports ch0DataOut]
set_property SLEW SLOW [get_ports ch0DataOut]
set_property IOSTANDARD LVCMOS33 [get_ports sdiOut]
set_property DRIVE 12 [get_ports sdiOut]
set_property SLEW SLOW [get_ports sdiOut]

set_property IOSTANDARD LVCMOS33 [get_ports DQMOut]
set_property DRIVE 12 [get_ports DQMOut]
set_property SLEW SLOW [get_ports DQMOut]

set_property DRIVE 12 [get_ports lockLed0n]
set_property SLEW SLOW [get_ports lockLed0n]
set_property DRIVE 12 [get_ports lockLed1n]
set_property SLEW SLOW [get_ports lockLed1n]

set_property IOSTANDARD LVCMOS33 [get_ports pll0_REF]
set_property IOSTANDARD LVCMOS33 [get_ports pll0_OUT1]
set_property IOSTANDARD LVCMOS33 [get_ports pll1_REF]
set_property IOSTANDARD LVCMOS33 [get_ports pll1_OUT1]
set_property DRIVE 12 [get_ports pll0_REF]
set_property DRIVE 12 [get_ports pll1_REF]
set_property SLEW FAST [get_ports pll0_REF]
set_property SLEW FAST [get_ports pll1_REF]

set_property IOSTANDARD LVCMOS33 [get_ports spiClk]
set_property IOSTANDARD LVCMOS33 [get_ports spiCSn]
set_property IOSTANDARD LVCMOS33 [get_ports spiDataIn]
set_property IOSTANDARD LVCMOS33 [get_ports spiDataOut]
set_property DRIVE 12 [get_ports spiDataOut]
set_property SLEW SLOW [get_ports spiDataOut]

set_property IOSTANDARD LVCMOS33 [get_ports spiFlashCSn]
set_property IOSTANDARD LVCMOS33 [get_ports spiFlashMOSI]
set_property IOSTANDARD LVCMOS33 [get_ports spiFlashMISO]
set_property DRIVE 12 [get_ports spiFlashCSn]
set_property DRIVE 12 [get_ports spiFlashMOSI]
set_property SLEW SLOW [get_ports spiFlashCSn]
set_property SLEW SLOW [get_ports spiFlashMOSI]

set_property IOSTANDARD LVCMOS33 [get_ports amAdcDataIn]
set_property IOSTANDARD LVCMOS33 [get_ports amAdcClk]
set_property DRIVE 12 [get_ports amAdcClk]
set_property SLEW SLOW [get_ports amAdcClk]
set_property IOSTANDARD LVCMOS33 [get_ports amAdcCSn]
set_property DRIVE 12 [get_ports amAdcCSn]
set_property SLEW SLOW [get_ports amAdcCSn]

set_property IOSTANDARD LVCMOS33 [get_ports amDacDataOut]
set_property DRIVE 12 [get_ports amDacDataOut]
set_property SLEW SLOW [get_ports amDacDataOut]
set_property IOSTANDARD LVCMOS33 [get_ports amDacClk]
set_property DRIVE 12 [get_ports amDacClk]
set_property SLEW SLOW [get_ports amDacClk]
set_property IOSTANDARD LVCMOS33 [get_ports amDacCSn]
set_property DRIVE 12 [get_ports amDacCSn]
set_property SLEW SLOW [get_ports amDacCSn]

set_property IOSTANDARD LVCMOS33 [get_ports lockLed0n]
set_property IOSTANDARD LVCMOS33 [get_ports lockLed1n]

set_property IOSTANDARD LVCMOS33 [get_ports {video1OutSelect[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video1OutSelect[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video0OutSelect[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video0OutSelect[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {video1InSelect[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video1InSelect[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video0InSelect[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video0InSelect[0]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]


#[Place 30-876] Port 'adcClk'  is assigned to PACKAGE_PIN 'D18'  which can only be used as the N side of a differential clock input.
#Please use the following constraint(s) to pass this DRC check:
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {systemClock/inst/clk_in1_systemClock}]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets spiClk_IBUF]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets BS_PllOut_IBUF]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pll0_OUT1_IBUF]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pll1_OUT1_IBUF]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets dac1_clk_OBUF]

set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]




