// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __mcalcAA_varinx18BNgs_H__
#define __mcalcAA_varinx18BNgs_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct mcalcAA_varinx18BNgs_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 21;
  static const unsigned AddressRange = 512;
  static const unsigned AddressWidth = 9;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in <sc_lv<AddressWidth> > address1;
sc_core::sc_in <sc_logic> ce1;
sc_core::sc_out <sc_lv<DataWidth> > q1;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(mcalcAA_varinx18BNgs_ram) {
        ram[0] = "0b111100110110010001000";
        ram[1] = "0b111101010110100001001";
        ram[2] = "0b111101110110110001010";
        ram[3] = "0b111110010111000001011";
        ram[4] = "0b111110110111010001100";
        ram[5] = "0b111111010111100001101";
        ram[6] = "0b111111110111110001110";
        ram[7] = "0b110000010000000001111";
        ram[8] = "0b110000110000010010000";
        ram[9] = "0b110001010000100010001";
        ram[10] = "0b110001110000110010010";
        ram[11] = "0b110010010001000010011";
        ram[12] = "0b110010110001010010100";
        ram[13] = "0b110011010001100010101";
        ram[14] = "0b110011110001110010110";
        ram[15] = "0b110100010010000010111";
        ram[16] = "0b110100110010010011000";
        ram[17] = "0b110101010010100011001";
        ram[18] = "0b110101110010110011010";
        ram[19] = "0b110110010011000011011";
        ram[20] = "0b110110110011010011100";
        ram[21] = "0b110111010011100011101";
        ram[22] = "0b110111110011110011110";
        ram[23] = "0b111000010100000011111";
        ram[24] = "0b111000110100010000000";
        ram[25] = "0b111001010100100000001";
        ram[26] = "0b111001110100110000010";
        ram[27] = "0b111010010101000000011";
        ram[28] = "0b111010110101010000100";
        ram[29] = "0b111011010101100000101";
        ram[30] = "0b111011110101110000110";
        ram[31] = "0b111100010110000000111";
        ram[32] = "0b111011101011000001111";
        ram[33] = "0b111100001011010010000";
        ram[34] = "0b111100101011100010001";
        ram[35] = "0b111101001011110010010";
        ram[36] = "0b111101101100000010011";
        ram[37] = "0b111110001100010010100";
        ram[38] = "0b111110101100100010101";
        ram[39] = "0b111111001100110010110";
        ram[40] = "0b111111101101000010111";
        ram[41] = "0b110000001101010011000";
        ram[42] = "0b110000101101100011001";
        ram[43] = "0b110001001101110011010";
        ram[44] = "0b110001101110000011011";
        ram[45] = "0b110010001110010011100";
        ram[46] = "0b110010101110100011101";
        ram[47] = "0b110011001110110011110";
        ram[48] = "0b110011101111000011111";
        ram[49] = "0b110100001111010000000";
        ram[50] = "0b110100101111100000001";
        ram[51] = "0b110101001111110000010";
        ram[52] = "0b110101101000000000011";
        ram[53] = "0b110110001000010000100";
        ram[54] = "0b110110101000100000101";
        ram[55] = "0b110111001000110000110";
        ram[56] = "0b110111101001000000111";
        ram[57] = "0b111000001001010001000";
        ram[58] = "0b111000101001100001001";
        ram[59] = "0b111001001001110001010";
        ram[60] = "0b111001101010000001011";
        ram[61] = "0b111010001010010001100";
        ram[62] = "0b111010101010100001101";
        ram[63] = "0b111011001010110001110";
        ram[64] = "0b101001001101110000100";
        ram[65] = "0b101001101110000000101";
        ram[66] = "0b101010001110010000110";
        ram[67] = "0b101010101110100000111";
        ram[68] = "0b101011001110110001000";
        ram[69] = "0b101011101111000001001";
        ram[70] = "0b101100001111010001010";
        ram[71] = "0b101100101111100001011";
        ram[72] = "0b101101001111110001100";
        ram[73] = "0b101101101000000001101";
        ram[74] = "0b101110001000010001110";
        ram[75] = "0b101110101000100001111";
        ram[76] = "0b101111001000110010000";
        ram[77] = "0b101111101001000010001";
        ram[78] = "0b100000001001010010010";
        ram[79] = "0b100000101001100010011";
        ram[80] = "0b100001001001110010100";
        ram[81] = "0b100001101010000010101";
        ram[82] = "0b100010001010010010110";
        ram[83] = "0b100010101010100010111";
        ram[84] = "0b100011001010110011000";
        ram[85] = "0b100011101011000011001";
        ram[86] = "0b100100001011010011010";
        ram[87] = "0b100100101011100011011";
        ram[88] = "0b100101001011110011100";
        ram[89] = "0b100101101100000011101";
        ram[90] = "0b100110001100010011110";
        ram[91] = "0b100110101100100011111";
        ram[92] = "0b100111001100110000000";
        ram[93] = "0b100111101101000000001";
        ram[94] = "0b101000001101010000010";
        ram[95] = "0b101000101101100000011";
        ram[96] = "0b111010010101100101000";
        ram[97] = "0b111010110101110101001";
        ram[98] = "0b111011010110000101010";
        ram[99] = "0b111011110110010101011";
        ram[100] = "0b111100010110100101100";
        ram[101] = "0b111100110110110101101";
        ram[102] = "0b111101010111000101110";
        ram[103] = "0b111101110111010101111";
        ram[104] = "0b111110010111100110000";
        ram[105] = "0b111110110111110110001";
        ram[106] = "0b111111010000000110010";
        ram[107] = "0b111111110000010110011";
        ram[108] = "0b110000010000100110100";
        ram[109] = "0b110000110000110110101";
        ram[110] = "0b110001010001000110110";
        ram[111] = "0b110001110001010110111";
        ram[112] = "0b110010010001100111000";
        ram[113] = "0b110010110001110111001";
        ram[114] = "0b110011010010000111010";
        ram[115] = "0b110011110010010111011";
        ram[116] = "0b110100010010100111100";
        ram[117] = "0b110100110010110111101";
        ram[118] = "0b110101010011000111110";
        ram[119] = "0b110101110011010111111";
        ram[120] = "0b110110010011100100000";
        ram[121] = "0b110110110011110100001";
        ram[122] = "0b110111010100000100010";
        ram[123] = "0b110111110100010100011";
        ram[124] = "0b111000010100100100100";
        ram[125] = "0b111000110100110100101";
        ram[126] = "0b111001010101000100110";
        ram[127] = "0b111001110101010100111";
        for (unsigned i = 128; i < 512 ; i = i + 1) {
            ram[i] = "0b000000000000000000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();


SC_METHOD(prc_write_1);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


void prc_write_1()
{
    if (ce1.read() == sc_dt::Log_1) 
    {
            if(address1.read().is_01() && address1.read().to_uint()<AddressRange)
              q1 = ram[address1.read().to_uint()];
            else
              q1 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(mcalcAA_varinx18BNgs) {


static const unsigned DataWidth = 21;
static const unsigned AddressRange = 512;
static const unsigned AddressWidth = 9;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in <sc_lv<AddressWidth> > address1;
sc_core::sc_in<sc_logic> ce1;
sc_core::sc_out <sc_lv<DataWidth> > q1;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


mcalcAA_varinx18BNgs_ram* meminst;


SC_CTOR(mcalcAA_varinx18BNgs) {
meminst = new mcalcAA_varinx18BNgs_ram("mcalcAA_varinx18BNgs_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->address1(address1);
meminst->ce1(ce1);
meminst->q1(q1);

meminst->reset(reset);
meminst->clk(clk);
}
~mcalcAA_varinx18BNgs() {
    delete meminst;
}


};//endmodule
#endif
