// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mcalcF (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        nIterationCounter,
        Peta_tabf_V_0,
        Lam_tabf_V_0,
        Peta_tabf_V_1,
        Lam_tabf_V_1,
        Peta_tabf_V_2,
        Lam_tabf_V_2,
        Peta_tabf_V_3,
        Lam_tabf_V_3,
        Peta_tabf_V_4,
        Lam_tabf_V_4,
        Peta_tabf_V_5,
        Lam_tabf_V_5,
        Peta_tabf_V_6,
        Lam_tabf_V_6,
        Peta_tabf_V_7,
        Lam_tabf_V_7,
        Peta_tabf_V_8,
        Lam_tabf_V_8,
        Peta_tabf_V_9,
        Lam_tabf_V_9,
        Eta_ans_4_V_0,
        Eta_ans_4_V_0_ap_vld,
        Eta_ans_4_V_1,
        Eta_ans_4_V_1_ap_vld,
        Eta_ans_4_V_2,
        Eta_ans_4_V_2_ap_vld,
        Eta_ans_4_V_3,
        Eta_ans_4_V_3_ap_vld,
        Eta_ans_4_V_4,
        Eta_ans_4_V_4_ap_vld,
        Eta_ans_4_V_5,
        Eta_ans_4_V_5_ap_vld,
        Eta_ans_4_V_6,
        Eta_ans_4_V_6_ap_vld,
        Eta_ans_4_V_7,
        Eta_ans_4_V_7_ap_vld,
        Eta_ans_4_V_8,
        Eta_ans_4_V_8_ap_vld,
        Eta_ans_4_V_9,
        Eta_ans_4_V_9_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv9_7E = 9'b1111110;
parameter    ap_const_lv9_3E = 9'b111110;
parameter    ap_const_lv9_1E = 9'b11110;
parameter    ap_const_lv9_E = 9'b1110;
parameter    ap_const_lv9_6 = 9'b110;
parameter    ap_const_lv9_2 = 9'b10;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv7_1F = 7'b11111;
parameter    ap_const_lv7_3F = 7'b111111;
parameter    ap_const_lv7_7 = 7'b111;
parameter    ap_const_lv7_F = 7'b1111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] nIterationCounter;
input  [7:0] Peta_tabf_V_0;
input  [7:0] Lam_tabf_V_0;
input  [7:0] Peta_tabf_V_1;
input  [7:0] Lam_tabf_V_1;
input  [7:0] Peta_tabf_V_2;
input  [7:0] Lam_tabf_V_2;
input  [7:0] Peta_tabf_V_3;
input  [7:0] Lam_tabf_V_3;
input  [7:0] Peta_tabf_V_4;
input  [7:0] Lam_tabf_V_4;
input  [7:0] Peta_tabf_V_5;
input  [7:0] Lam_tabf_V_5;
input  [7:0] Peta_tabf_V_6;
input  [7:0] Lam_tabf_V_6;
input  [7:0] Peta_tabf_V_7;
input  [7:0] Lam_tabf_V_7;
input  [7:0] Peta_tabf_V_8;
input  [7:0] Lam_tabf_V_8;
input  [7:0] Peta_tabf_V_9;
input  [7:0] Lam_tabf_V_9;
output  [7:0] Eta_ans_4_V_0;
output   Eta_ans_4_V_0_ap_vld;
output  [7:0] Eta_ans_4_V_1;
output   Eta_ans_4_V_1_ap_vld;
output  [7:0] Eta_ans_4_V_2;
output   Eta_ans_4_V_2_ap_vld;
output  [7:0] Eta_ans_4_V_3;
output   Eta_ans_4_V_3_ap_vld;
output  [7:0] Eta_ans_4_V_4;
output   Eta_ans_4_V_4_ap_vld;
output  [7:0] Eta_ans_4_V_5;
output   Eta_ans_4_V_5_ap_vld;
output  [7:0] Eta_ans_4_V_6;
output   Eta_ans_4_V_6_ap_vld;
output  [7:0] Eta_ans_4_V_7;
output   Eta_ans_4_V_7_ap_vld;
output  [7:0] Eta_ans_4_V_8;
output   Eta_ans_4_V_8_ap_vld;
output  [7:0] Eta_ans_4_V_9;
output   Eta_ans_4_V_9_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Eta_ans_4_V_0_ap_vld;
reg Eta_ans_4_V_1_ap_vld;
reg Eta_ans_4_V_2_ap_vld;
reg Eta_ans_4_V_3_ap_vld;
reg Eta_ans_4_V_4_ap_vld;
reg Eta_ans_4_V_5_ap_vld;
reg Eta_ans_4_V_6_ap_vld;
reg Eta_ans_4_V_7_ap_vld;
reg Eta_ans_4_V_8_ap_vld;
reg Eta_ans_4_V_9_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
wire   [0:0] tmp_fu_114_p2;
reg   [0:0] tmp_reg_2749;
wire   [0:0] tmp_334_fu_149_p3;
reg   [0:0] tmp_334_reg_2763;
wire   [6:0] rhs_V_s_fu_311_p3;
reg   [6:0] rhs_V_s_reg_2769;
wire   [0:0] tmp_335_fu_348_p3;
reg   [0:0] tmp_335_reg_2774;
wire   [6:0] rhs_V_10_1_fu_510_p3;
reg   [6:0] rhs_V_10_1_reg_2780;
wire   [6:0] r_V_59_1_fu_518_p2;
reg   [6:0] r_V_59_1_reg_2785;
wire   [0:0] tmp_336_fu_553_p3;
reg   [0:0] tmp_336_reg_2791;
wire   [6:0] rhs_V_10_2_fu_715_p3;
reg   [6:0] rhs_V_10_2_reg_2798;
wire   [0:0] tmp_337_fu_752_p3;
reg   [0:0] tmp_337_reg_2805;
wire   [6:0] rhs_V_10_3_fu_914_p3;
reg   [6:0] rhs_V_10_3_reg_2811;
wire   [0:0] tmp_338_fu_951_p3;
reg   [0:0] tmp_338_reg_2817;
wire   [0:0] tmp_504_4_fu_973_p2;
reg   [0:0] tmp_504_4_reg_2824;
wire   [0:0] tmp_505_4_fu_979_p2;
reg   [0:0] tmp_505_4_reg_2830;
wire   [0:0] tmp_506_4_fu_985_p2;
reg   [0:0] tmp_506_4_reg_2835;
wire   [0:0] tmp_507_4_fu_991_p2;
reg   [0:0] tmp_507_4_reg_2840;
wire   [0:0] tmp_508_4_fu_997_p2;
reg   [0:0] tmp_508_4_reg_2846;
wire   [0:0] tmp_509_4_fu_1003_p2;
reg   [0:0] tmp_509_4_reg_2851;
wire   [0:0] sel_tmp111_fu_1015_p2;
reg   [0:0] sel_tmp111_reg_2856;
wire   [0:0] tmp_339_fu_1050_p3;
reg   [0:0] tmp_339_reg_2862;
wire   [0:0] tmp_504_5_fu_1072_p2;
reg   [0:0] tmp_504_5_reg_2869;
wire   [0:0] tmp_505_5_fu_1078_p2;
reg   [0:0] tmp_505_5_reg_2875;
wire   [0:0] tmp_506_5_fu_1084_p2;
reg   [0:0] tmp_506_5_reg_2881;
wire   [0:0] tmp_507_5_fu_1090_p2;
reg   [0:0] tmp_507_5_reg_2887;
wire   [0:0] tmp_508_5_fu_1096_p2;
reg   [0:0] tmp_508_5_reg_2893;
wire   [0:0] tmp_509_5_fu_1102_p2;
reg   [0:0] tmp_509_5_reg_2898;
wire   [0:0] tmp_340_fu_1137_p3;
reg   [0:0] tmp_340_reg_2903;
wire   [0:0] tmp_504_6_fu_1159_p2;
reg   [0:0] tmp_504_6_reg_2910;
wire   [0:0] tmp_505_6_fu_1165_p2;
reg   [0:0] tmp_505_6_reg_2916;
wire   [0:0] tmp_506_6_fu_1171_p2;
reg   [0:0] tmp_506_6_reg_2922;
wire   [0:0] tmp_507_6_fu_1177_p2;
reg   [0:0] tmp_507_6_reg_2928;
wire   [0:0] tmp_508_6_fu_1183_p2;
reg   [0:0] tmp_508_6_reg_2934;
wire   [0:0] tmp_509_6_fu_1189_p2;
reg   [0:0] tmp_509_6_reg_2939;
wire   [0:0] tmp_341_fu_1224_p3;
reg   [0:0] tmp_341_reg_2944;
wire   [0:0] tmp_504_7_fu_1246_p2;
reg   [0:0] tmp_504_7_reg_2950;
wire   [0:0] tmp_505_7_fu_1252_p2;
reg   [0:0] tmp_505_7_reg_2956;
wire   [0:0] tmp_506_7_fu_1258_p2;
reg   [0:0] tmp_506_7_reg_2962;
wire   [0:0] tmp_507_7_fu_1264_p2;
reg   [0:0] tmp_507_7_reg_2968;
wire   [0:0] tmp_508_7_fu_1270_p2;
reg   [0:0] tmp_508_7_reg_2974;
wire   [0:0] tmp_509_7_fu_1276_p2;
reg   [0:0] tmp_509_7_reg_2979;
wire   [0:0] tmp_342_fu_1311_p3;
reg   [0:0] tmp_342_reg_2984;
wire   [0:0] tmp_504_8_fu_1333_p2;
reg   [0:0] tmp_504_8_reg_2990;
wire   [0:0] tmp_505_8_fu_1339_p2;
reg   [0:0] tmp_505_8_reg_2996;
wire   [0:0] tmp_506_8_fu_1345_p2;
reg   [0:0] tmp_506_8_reg_3002;
wire   [0:0] tmp_507_8_fu_1351_p2;
reg   [0:0] tmp_507_8_reg_3008;
wire   [0:0] tmp_508_8_fu_1357_p2;
reg   [0:0] tmp_508_8_reg_3014;
wire   [0:0] tmp_509_8_fu_1363_p2;
reg   [0:0] tmp_509_8_reg_3019;
wire   [0:0] tmp_343_fu_1398_p3;
reg   [0:0] tmp_343_reg_3024;
wire   [0:0] tmp_504_9_fu_1420_p2;
reg   [0:0] tmp_504_9_reg_3030;
wire   [0:0] tmp_505_9_fu_1426_p2;
reg   [0:0] tmp_505_9_reg_3036;
wire   [0:0] tmp_506_9_fu_1432_p2;
reg   [0:0] tmp_506_9_reg_3042;
wire   [0:0] tmp_507_9_fu_1438_p2;
reg   [0:0] tmp_507_9_reg_3048;
wire   [0:0] tmp_508_9_fu_1444_p2;
reg   [0:0] tmp_508_9_reg_3054;
wire   [0:0] tmp_509_9_fu_1450_p2;
reg   [0:0] tmp_509_9_reg_3059;
wire   [7:0] p_s_fu_124_p3;
wire  signed [8:0] p_cast_fu_131_p1;
wire  signed [8:0] rhs_V_fu_139_p1;
wire   [8:0] vArg_V_fu_143_p2;
wire   [8:0] vArg_V_13_fu_157_p2;
wire   [8:0] vArg_V_s_fu_163_p3;
wire   [0:0] tmp_295_fu_171_p2;
wire   [0:0] tmp_300_fu_201_p2;
wire   [2:0] p_21_cast_cast_fu_207_p3;
wire   [2:0] sel_tmp_fu_215_p3;
wire   [0:0] tmp_296_fu_177_p2;
wire   [0:0] sel_tmp1_fu_227_p2;
wire   [0:0] tmp_297_fu_183_p2;
wire   [0:0] sel_tmp6_fu_239_p2;
wire   [0:0] sel_tmp7_fu_245_p2;
wire   [0:0] sel_tmp2_fu_233_p2;
wire   [0:0] tmp_314_fu_259_p2;
wire   [6:0] sel_tmp3_cast_fu_251_p3;
wire  signed [6:0] sel_tmp_cast_fu_223_p1;
wire   [0:0] tmp_298_fu_189_p2;
wire   [0:0] sel_tmp13_fu_273_p2;
wire   [0:0] tmp_299_fu_195_p2;
wire   [0:0] sel_tmp22_fu_285_p2;
wire   [0:0] sel_tmp23_fu_291_p2;
wire   [0:0] sel_tmp14_fu_279_p2;
wire   [0:0] tmp_315_fu_305_p2;
wire   [6:0] sel_tmp15_cast_fu_297_p3;
wire   [6:0] sel_tmp8_fu_265_p3;
wire   [7:0] p_61_1_fu_323_p3;
wire  signed [8:0] p_61_1_cast_fu_330_p1;
wire  signed [8:0] rhs_V_1_fu_338_p1;
wire   [8:0] vArg_V_1_fu_342_p2;
wire   [8:0] vArg_V_13_1_fu_356_p2;
wire   [8:0] vArg_V_14_1_fu_362_p3;
wire   [0:0] tmp_504_1_fu_370_p2;
wire   [0:0] tmp_509_1_fu_400_p2;
wire   [2:0] p_62_1_cast_cast_fu_406_p3;
wire   [2:0] sel_tmp26_fu_414_p3;
wire   [0:0] tmp_505_1_fu_376_p2;
wire   [0:0] sel_tmp27_fu_426_p2;
wire   [0:0] tmp_506_1_fu_382_p2;
wire   [0:0] sel_tmp32_fu_438_p2;
wire   [0:0] sel_tmp33_fu_444_p2;
wire   [0:0] sel_tmp28_fu_432_p2;
wire   [0:0] tmp_316_fu_458_p2;
wire   [6:0] sel_tmp29_cast_fu_450_p3;
wire  signed [6:0] sel_tmp26_cast_fu_422_p1;
wire   [0:0] tmp_507_1_fu_388_p2;
wire   [0:0] sel_tmp39_fu_472_p2;
wire   [0:0] tmp_508_1_fu_394_p2;
wire   [0:0] sel_tmp48_fu_484_p2;
wire   [0:0] sel_tmp49_fu_490_p2;
wire   [0:0] sel_tmp40_fu_478_p2;
wire   [0:0] tmp_317_fu_504_p2;
wire   [6:0] sel_tmp41_cast_fu_496_p3;
wire   [6:0] sel_tmp34_fu_464_p3;
wire   [7:0] p_61_2_fu_528_p3;
wire  signed [8:0] p_61_2_cast_fu_535_p1;
wire  signed [8:0] rhs_V_2_fu_543_p1;
wire   [8:0] vArg_V_2_fu_547_p2;
wire   [8:0] vArg_V_13_2_fu_561_p2;
wire   [8:0] vArg_V_14_2_fu_567_p3;
wire   [0:0] tmp_504_2_fu_575_p2;
wire   [0:0] tmp_509_2_fu_605_p2;
wire   [2:0] p_62_2_cast_cast_fu_611_p3;
wire   [2:0] sel_tmp52_fu_619_p3;
wire   [0:0] tmp_505_2_fu_581_p2;
wire   [0:0] sel_tmp53_fu_631_p2;
wire   [0:0] tmp_506_2_fu_587_p2;
wire   [0:0] sel_tmp58_fu_643_p2;
wire   [0:0] sel_tmp59_fu_649_p2;
wire   [0:0] sel_tmp54_fu_637_p2;
wire   [0:0] tmp_318_fu_663_p2;
wire   [6:0] sel_tmp55_cast_fu_655_p3;
wire  signed [6:0] sel_tmp52_cast_fu_627_p1;
wire   [0:0] tmp_507_2_fu_593_p2;
wire   [0:0] sel_tmp65_fu_677_p2;
wire   [0:0] tmp_508_2_fu_599_p2;
wire   [0:0] sel_tmp74_fu_689_p2;
wire   [0:0] sel_tmp75_fu_695_p2;
wire   [0:0] sel_tmp66_fu_683_p2;
wire   [0:0] tmp_319_fu_709_p2;
wire   [6:0] sel_tmp67_cast_fu_701_p3;
wire   [6:0] sel_tmp60_fu_669_p3;
wire   [7:0] p_61_3_fu_727_p3;
wire  signed [8:0] p_61_3_cast_fu_734_p1;
wire  signed [8:0] rhs_V_3_fu_742_p1;
wire   [8:0] vArg_V_3_fu_746_p2;
wire   [8:0] vArg_V_13_3_fu_760_p2;
wire   [8:0] vArg_V_14_3_fu_766_p3;
wire   [0:0] tmp_504_3_fu_774_p2;
wire   [0:0] tmp_509_3_fu_804_p2;
wire   [2:0] p_62_3_cast_cast_fu_810_p3;
wire   [2:0] sel_tmp78_fu_818_p3;
wire   [0:0] tmp_505_3_fu_780_p2;
wire   [0:0] sel_tmp79_fu_830_p2;
wire   [0:0] tmp_506_3_fu_786_p2;
wire   [0:0] sel_tmp84_fu_842_p2;
wire   [0:0] sel_tmp85_fu_848_p2;
wire   [0:0] sel_tmp80_fu_836_p2;
wire   [0:0] tmp_320_fu_862_p2;
wire   [6:0] sel_tmp81_cast_fu_854_p3;
wire  signed [6:0] sel_tmp78_cast_fu_826_p1;
wire   [0:0] tmp_507_3_fu_792_p2;
wire   [0:0] sel_tmp91_fu_876_p2;
wire   [0:0] tmp_508_3_fu_798_p2;
wire   [0:0] sel_tmp100_fu_888_p2;
wire   [0:0] sel_tmp101_fu_894_p2;
wire   [0:0] sel_tmp92_fu_882_p2;
wire   [0:0] tmp_321_fu_908_p2;
wire   [6:0] sel_tmp93_cast_fu_900_p3;
wire   [6:0] sel_tmp86_fu_868_p3;
wire   [7:0] p_61_4_fu_926_p3;
wire  signed [8:0] p_61_4_cast_fu_933_p1;
wire  signed [8:0] rhs_V_4_fu_941_p1;
wire   [8:0] vArg_V_4_fu_945_p2;
wire   [8:0] vArg_V_13_4_fu_959_p2;
wire   [8:0] vArg_V_14_4_fu_965_p3;
wire   [0:0] sel_tmp110_fu_1009_p2;
wire   [7:0] p_61_5_fu_1025_p3;
wire  signed [8:0] p_61_5_cast_fu_1032_p1;
wire  signed [8:0] rhs_V_5_fu_1040_p1;
wire   [8:0] vArg_V_5_fu_1044_p2;
wire   [8:0] vArg_V_13_5_fu_1058_p2;
wire   [8:0] vArg_V_14_5_fu_1064_p3;
wire   [7:0] p_61_6_fu_1112_p3;
wire  signed [8:0] p_61_6_cast_fu_1119_p1;
wire  signed [8:0] rhs_V_6_fu_1127_p1;
wire   [8:0] vArg_V_6_fu_1131_p2;
wire   [8:0] vArg_V_13_6_fu_1145_p2;
wire   [8:0] vArg_V_14_6_fu_1151_p3;
wire   [7:0] p_61_7_fu_1199_p3;
wire  signed [8:0] p_61_7_cast_fu_1206_p1;
wire  signed [8:0] rhs_V_7_fu_1214_p1;
wire   [8:0] vArg_V_7_fu_1218_p2;
wire   [8:0] vArg_V_13_7_fu_1232_p2;
wire   [8:0] vArg_V_14_7_fu_1238_p3;
wire   [7:0] p_61_8_fu_1286_p3;
wire  signed [8:0] p_61_8_cast_fu_1293_p1;
wire  signed [8:0] rhs_V_8_fu_1301_p1;
wire   [8:0] vArg_V_8_fu_1305_p2;
wire   [8:0] vArg_V_13_8_fu_1319_p2;
wire   [8:0] vArg_V_14_8_fu_1325_p3;
wire   [7:0] p_61_9_fu_1373_p3;
wire  signed [8:0] p_61_9_cast_fu_1380_p1;
wire  signed [8:0] rhs_V_9_fu_1388_p1;
wire   [8:0] vArg_V_9_fu_1392_p2;
wire   [8:0] vArg_V_13_9_fu_1406_p2;
wire   [8:0] vArg_V_14_9_fu_1412_p3;
wire   [0:0] tmp_515_1_fu_1456_p2;
wire   [0:0] rev7_fu_1460_p2;
wire   [6:0] r_V_60_2_fu_1465_p2;
wire   [0:0] tmp_517_2_fu_1469_p2;
wire   [0:0] rev10_fu_1475_p2;
wire   [2:0] p_62_4_cast_cast_fu_1496_p3;
wire   [2:0] sel_tmp104_fu_1503_p3;
wire   [0:0] sel_tmp105_fu_1514_p2;
wire   [0:0] sel_tmp106_fu_1519_p2;
wire   [0:0] tmp_322_fu_1531_p2;
wire   [6:0] sel_tmp107_cast_fu_1524_p3;
wire  signed [6:0] sel_tmp104_cast_fu_1510_p1;
wire   [0:0] sel_tmp117_fu_1544_p2;
wire   [0:0] sel_tmp126_fu_1554_p2;
wire   [0:0] sel_tmp127_fu_1559_p2;
wire   [0:0] sel_tmp118_fu_1549_p2;
wire   [0:0] tmp_323_fu_1572_p2;
wire   [6:0] sel_tmp119_cast_fu_1564_p3;
wire   [6:0] sel_tmp112_fu_1536_p3;
wire   [6:0] r_V_61_3_fu_1480_p2;
wire   [6:0] rhs_V_10_4_fu_1578_p3;
wire   [0:0] tmp_519_3_fu_1485_p2;
wire   [0:0] rev13_fu_1491_p2;
wire   [2:0] p_62_5_cast_cast_fu_1603_p3;
wire   [2:0] sel_tmp130_fu_1610_p3;
wire   [0:0] sel_tmp131_fu_1621_p2;
wire   [0:0] sel_tmp136_fu_1631_p2;
wire   [0:0] sel_tmp137_fu_1636_p2;
wire   [0:0] sel_tmp132_fu_1626_p2;
wire   [0:0] tmp_324_fu_1649_p2;
wire   [6:0] sel_tmp133_cast_fu_1641_p3;
wire  signed [6:0] sel_tmp130_cast_fu_1617_p1;
wire   [0:0] sel_tmp143_fu_1663_p2;
wire   [0:0] sel_tmp152_fu_1673_p2;
wire   [0:0] sel_tmp153_fu_1678_p2;
wire   [0:0] sel_tmp144_fu_1668_p2;
wire   [0:0] tmp_325_fu_1691_p2;
wire   [6:0] sel_tmp145_cast_fu_1683_p3;
wire   [6:0] sel_tmp138_fu_1655_p3;
wire   [6:0] r_V_62_4_fu_1586_p2;
wire   [6:0] rhs_V_10_5_fu_1697_p3;
wire   [0:0] tmp_521_4_fu_1592_p2;
wire   [0:0] rev16_fu_1598_p2;
wire   [2:0] p_62_6_cast_cast_fu_1722_p3;
wire   [2:0] sel_tmp156_fu_1729_p3;
wire   [0:0] sel_tmp157_fu_1740_p2;
wire   [0:0] sel_tmp162_fu_1750_p2;
wire   [0:0] sel_tmp163_fu_1755_p2;
wire   [0:0] sel_tmp158_fu_1745_p2;
wire   [0:0] tmp_326_fu_1768_p2;
wire   [6:0] sel_tmp159_cast_fu_1760_p3;
wire  signed [6:0] sel_tmp156_cast_fu_1736_p1;
wire   [0:0] sel_tmp169_fu_1782_p2;
wire   [0:0] sel_tmp178_fu_1792_p2;
wire   [0:0] sel_tmp179_fu_1797_p2;
wire   [0:0] sel_tmp170_fu_1787_p2;
wire   [0:0] tmp_327_fu_1810_p2;
wire   [6:0] sel_tmp171_cast_fu_1802_p3;
wire   [6:0] sel_tmp164_fu_1774_p3;
wire   [6:0] r_V_63_5_fu_1705_p2;
wire   [6:0] rhs_V_10_6_fu_1816_p3;
wire   [0:0] tmp_523_5_fu_1711_p2;
wire   [0:0] rev19_fu_1717_p2;
wire   [2:0] p_62_7_cast_cast_fu_1841_p3;
wire   [2:0] sel_tmp182_fu_1848_p3;
wire   [0:0] sel_tmp183_fu_1859_p2;
wire   [0:0] sel_tmp188_fu_1869_p2;
wire   [0:0] sel_tmp189_fu_1874_p2;
wire   [0:0] sel_tmp184_fu_1864_p2;
wire   [0:0] tmp_328_fu_1887_p2;
wire   [6:0] sel_tmp185_cast_fu_1879_p3;
wire  signed [6:0] sel_tmp182_cast_fu_1855_p1;
wire   [0:0] sel_tmp195_fu_1901_p2;
wire   [0:0] sel_tmp204_fu_1911_p2;
wire   [0:0] sel_tmp205_fu_1916_p2;
wire   [0:0] sel_tmp196_fu_1906_p2;
wire   [0:0] tmp_329_fu_1929_p2;
wire   [6:0] sel_tmp197_cast_fu_1921_p3;
wire   [6:0] sel_tmp190_fu_1893_p3;
wire   [6:0] r_V_64_6_fu_1824_p2;
wire   [6:0] rhs_V_10_7_fu_1935_p3;
wire   [0:0] tmp_525_6_fu_1830_p2;
wire   [0:0] rev22_fu_1836_p2;
wire   [2:0] p_62_8_cast_cast_fu_1960_p3;
wire   [2:0] sel_tmp208_fu_1967_p3;
wire   [0:0] sel_tmp209_fu_1978_p2;
wire   [0:0] sel_tmp214_fu_1988_p2;
wire   [0:0] sel_tmp215_fu_1993_p2;
wire   [0:0] sel_tmp210_fu_1983_p2;
wire   [0:0] tmp_330_fu_2006_p2;
wire   [6:0] sel_tmp211_cast_fu_1998_p3;
wire  signed [6:0] sel_tmp208_cast_fu_1974_p1;
wire   [0:0] sel_tmp221_fu_2020_p2;
wire   [0:0] sel_tmp230_fu_2030_p2;
wire   [0:0] sel_tmp231_fu_2035_p2;
wire   [0:0] sel_tmp222_fu_2025_p2;
wire   [0:0] tmp_331_fu_2048_p2;
wire   [6:0] sel_tmp223_cast_fu_2040_p3;
wire   [6:0] sel_tmp216_fu_2012_p3;
wire   [6:0] r_V_65_7_fu_1943_p2;
wire   [6:0] rhs_V_10_8_fu_2054_p3;
wire   [6:0] r_V_66_8_fu_2062_p2;
wire   [0:0] tmp_527_7_fu_1949_p2;
wire   [0:0] rev_fu_1955_p2;
wire   [2:0] p_62_9_cast_cast_fu_2083_p3;
wire   [2:0] sel_tmp234_fu_2090_p3;
wire   [0:0] sel_tmp235_fu_2101_p2;
wire   [0:0] sel_tmp237_fu_2111_p2;
wire   [0:0] sel_tmp238_fu_2116_p2;
wire   [0:0] sel_tmp236_fu_2106_p2;
wire   [0:0] tmp_332_fu_2129_p2;
wire   [6:0] sel_tmp237_cast_fu_2121_p3;
wire  signed [6:0] sel_tmp234_cast_fu_2097_p1;
wire   [0:0] sel_tmp240_fu_2143_p2;
wire   [0:0] sel_tmp242_fu_2153_p2;
wire   [0:0] sel_tmp243_fu_2158_p2;
wire   [0:0] sel_tmp241_fu_2148_p2;
wire   [0:0] tmp_333_fu_2171_p2;
wire   [6:0] sel_tmp249_cast_fu_2163_p3;
wire   [6:0] sel_tmp239_fu_2135_p3;
wire   [6:0] tmp280_fu_2191_p2;
wire   [6:0] tmp279_fu_2185_p2;
wire   [6:0] rhs_V_10_9_fu_2177_p3;
wire   [6:0] tmp283_fu_2207_p2;
wire   [6:0] tmp284_fu_2212_p2;
wire   [6:0] tmp282_fu_2203_p2;
wire   [6:0] tmp285_fu_2218_p2;
wire   [6:0] tmp281_fu_2197_p2;
wire   [6:0] r_V_57_9_fu_2224_p2;
wire   [0:0] tmp287_fu_2238_p2;
wire   [0:0] tmp286_fu_2234_p2;
wire   [0:0] tmp290_fu_2252_p2;
wire   [0:0] tmp291_fu_2256_p2;
wire   [0:0] tmp289_fu_2248_p2;
wire   [0:0] tmp292_fu_2262_p2;
wire   [0:0] tmp288_fu_2242_p2;
wire   [6:0] tmp293_fu_2274_p2;
wire   [6:0] tmp294_fu_2278_p2;
wire   [6:0] r_V_58_9_fu_2284_p2;
wire   [0:0] tmp295_fu_2294_p2;
wire   [0:0] tmp296_fu_2298_p2;
wire   [6:0] tmp297_fu_2310_p2;
wire   [6:0] tmp298_fu_2315_p2;
wire   [6:0] r_V_59_9_fu_2321_p2;
wire   [0:0] tmp300_fu_2337_p2;
wire   [0:0] tmp299_fu_2331_p2;
wire   [0:0] tmp302_fu_2347_p2;
wire   [0:0] tmp303_fu_2351_p2;
wire   [0:0] tmp301_fu_2341_p2;
wire   [6:0] tmp304_fu_2363_p2;
wire   [6:0] tmp307_fu_2381_p2;
wire   [6:0] tmp306_fu_2375_p2;
wire   [6:0] tmp308_fu_2387_p2;
wire   [6:0] tmp305_fu_2369_p2;
wire   [6:0] r_V_60_9_fu_2393_p2;
wire   [0:0] tmp309_fu_2403_p2;
wire   [6:0] tmp310_fu_2415_p2;
wire   [6:0] tmp311_fu_2421_p2;
wire   [6:0] r_V_61_9_fu_2427_p2;
wire   [0:0] tmp312_fu_2437_p2;
wire   [6:0] tmp313_fu_2449_p2;
wire   [6:0] tmp314_fu_2455_p2;
wire   [6:0] r_V_62_9_fu_2461_p2;
wire   [0:0] tmp315_fu_2471_p2;
wire   [6:0] tmp316_fu_2483_p2;
wire   [6:0] r_V_63_9_fu_2489_p2;
wire   [0:0] tmp317_fu_2499_p2;
wire   [6:0] tmp318_fu_2511_p2;
wire   [6:0] r_V_64_9_fu_2517_p2;
wire   [6:0] r_V_65_9_fu_2533_p2;
wire   [0:0] rev23_fu_2078_p2;
wire   [7:0] r_V_57_9_cast_fu_2230_p1;
wire   [0:0] tmp_511_9_fu_2268_p2;
wire   [7:0] mt11_fu_2549_p2;
wire   [7:0] r_V_58_9_cast_fu_2290_p1;
wire   [0:0] tmp_513_9_fu_2304_p2;
wire   [7:0] mt13_fu_2569_p2;
wire   [7:0] r_V_59_9_cast_fu_2327_p1;
wire   [0:0] tmp_515_9_fu_2357_p2;
wire   [7:0] mt15_fu_2589_p2;
wire   [7:0] r_V_60_9_cast_fu_2399_p1;
wire   [0:0] tmp_517_9_fu_2409_p2;
wire   [7:0] mt14_fu_2609_p2;
wire   [7:0] r_V_61_9_cast_fu_2433_p1;
wire   [0:0] tmp_519_9_fu_2443_p2;
wire   [7:0] mt12_fu_2629_p2;
wire   [7:0] r_V_62_9_cast_fu_2467_p1;
wire   [0:0] tmp_521_9_fu_2477_p2;
wire   [7:0] mt10_fu_2649_p2;
wire   [7:0] r_V_63_9_cast_fu_2495_p1;
wire   [0:0] tmp_523_9_fu_2505_p2;
wire   [7:0] mt8_fu_2669_p2;
wire   [7:0] r_V_64_9_cast_fu_2523_p1;
wire   [0:0] tmp_525_9_fu_2527_p2;
wire   [7:0] mt6_fu_2689_p2;
wire   [7:0] r_V_65_9_cast_fu_2539_p1;
wire   [0:0] tmp_527_9_fu_2543_p2;
wire   [7:0] mt4_fu_2709_p2;
wire   [7:0] r_V_66_8_cast_fu_2068_p1;
wire   [0:0] tmp_529_8_fu_2072_p2;
wire   [7:0] mt_fu_2729_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_pipeline_idle_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'b1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        r_V_59_1_reg_2785[6 : 1] <= r_V_59_1_fu_518_p2[6 : 1];
        rhs_V_10_1_reg_2780[6 : 1] <= rhs_V_10_1_fu_510_p3[6 : 1];
        rhs_V_10_2_reg_2798[6 : 1] <= rhs_V_10_2_fu_715_p3[6 : 1];
        rhs_V_10_3_reg_2811[6 : 1] <= rhs_V_10_3_fu_914_p3[6 : 1];
        rhs_V_s_reg_2769[6 : 1] <= rhs_V_s_fu_311_p3[6 : 1];
        sel_tmp111_reg_2856 <= sel_tmp111_fu_1015_p2;
        tmp_334_reg_2763 <= vArg_V_fu_143_p2[ap_const_lv32_8];
        tmp_335_reg_2774 <= vArg_V_1_fu_342_p2[ap_const_lv32_8];
        tmp_336_reg_2791 <= vArg_V_2_fu_547_p2[ap_const_lv32_8];
        tmp_337_reg_2805 <= vArg_V_3_fu_746_p2[ap_const_lv32_8];
        tmp_338_reg_2817 <= vArg_V_4_fu_945_p2[ap_const_lv32_8];
        tmp_339_reg_2862 <= vArg_V_5_fu_1044_p2[ap_const_lv32_8];
        tmp_340_reg_2903 <= vArg_V_6_fu_1131_p2[ap_const_lv32_8];
        tmp_341_reg_2944 <= vArg_V_7_fu_1218_p2[ap_const_lv32_8];
        tmp_342_reg_2984 <= vArg_V_8_fu_1305_p2[ap_const_lv32_8];
        tmp_343_reg_3024 <= vArg_V_9_fu_1392_p2[ap_const_lv32_8];
        tmp_504_4_reg_2824 <= tmp_504_4_fu_973_p2;
        tmp_504_5_reg_2869 <= tmp_504_5_fu_1072_p2;
        tmp_504_6_reg_2910 <= tmp_504_6_fu_1159_p2;
        tmp_504_7_reg_2950 <= tmp_504_7_fu_1246_p2;
        tmp_504_8_reg_2990 <= tmp_504_8_fu_1333_p2;
        tmp_504_9_reg_3030 <= tmp_504_9_fu_1420_p2;
        tmp_505_4_reg_2830 <= tmp_505_4_fu_979_p2;
        tmp_505_5_reg_2875 <= tmp_505_5_fu_1078_p2;
        tmp_505_6_reg_2916 <= tmp_505_6_fu_1165_p2;
        tmp_505_7_reg_2956 <= tmp_505_7_fu_1252_p2;
        tmp_505_8_reg_2996 <= tmp_505_8_fu_1339_p2;
        tmp_505_9_reg_3036 <= tmp_505_9_fu_1426_p2;
        tmp_506_4_reg_2835 <= tmp_506_4_fu_985_p2;
        tmp_506_5_reg_2881 <= tmp_506_5_fu_1084_p2;
        tmp_506_6_reg_2922 <= tmp_506_6_fu_1171_p2;
        tmp_506_7_reg_2962 <= tmp_506_7_fu_1258_p2;
        tmp_506_8_reg_3002 <= tmp_506_8_fu_1345_p2;
        tmp_506_9_reg_3042 <= tmp_506_9_fu_1432_p2;
        tmp_507_4_reg_2840 <= tmp_507_4_fu_991_p2;
        tmp_507_5_reg_2887 <= tmp_507_5_fu_1090_p2;
        tmp_507_6_reg_2928 <= tmp_507_6_fu_1177_p2;
        tmp_507_7_reg_2968 <= tmp_507_7_fu_1264_p2;
        tmp_507_8_reg_3008 <= tmp_507_8_fu_1351_p2;
        tmp_507_9_reg_3048 <= tmp_507_9_fu_1438_p2;
        tmp_508_4_reg_2846 <= tmp_508_4_fu_997_p2;
        tmp_508_5_reg_2893 <= tmp_508_5_fu_1096_p2;
        tmp_508_6_reg_2934 <= tmp_508_6_fu_1183_p2;
        tmp_508_7_reg_2974 <= tmp_508_7_fu_1270_p2;
        tmp_508_8_reg_3014 <= tmp_508_8_fu_1357_p2;
        tmp_508_9_reg_3054 <= tmp_508_9_fu_1444_p2;
        tmp_509_4_reg_2851 <= tmp_509_4_fu_1003_p2;
        tmp_509_5_reg_2898 <= tmp_509_5_fu_1102_p2;
        tmp_509_6_reg_2939 <= tmp_509_6_fu_1189_p2;
        tmp_509_7_reg_2979 <= tmp_509_7_fu_1276_p2;
        tmp_509_8_reg_3019 <= tmp_509_8_fu_1363_p2;
        tmp_509_9_reg_3059 <= tmp_509_9_fu_1450_p2;
        tmp_reg_2749 <= tmp_fu_114_p2;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_0_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_1_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_2_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_3_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_4_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_5_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_6_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_7_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_8_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        Eta_ans_4_V_9_ap_vld = 1'b1;
    end else begin
        Eta_ans_4_V_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter0)) | (~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_pipeline_idle_pp0 = 1'b1;
    end else begin
        ap_pipeline_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter0) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Eta_ans_4_V_0 = ((tmp_511_9_fu_2268_p2[0:0] === 1'b1) ? mt11_fu_2549_p2 : r_V_57_9_cast_fu_2230_p1);

assign Eta_ans_4_V_1 = ((tmp_513_9_fu_2304_p2[0:0] === 1'b1) ? mt13_fu_2569_p2 : r_V_58_9_cast_fu_2290_p1);

assign Eta_ans_4_V_2 = ((tmp_515_9_fu_2357_p2[0:0] === 1'b1) ? mt15_fu_2589_p2 : r_V_59_9_cast_fu_2327_p1);

assign Eta_ans_4_V_3 = ((tmp_517_9_fu_2409_p2[0:0] === 1'b1) ? mt14_fu_2609_p2 : r_V_60_9_cast_fu_2399_p1);

assign Eta_ans_4_V_4 = ((tmp_519_9_fu_2443_p2[0:0] === 1'b1) ? mt12_fu_2629_p2 : r_V_61_9_cast_fu_2433_p1);

assign Eta_ans_4_V_5 = ((tmp_521_9_fu_2477_p2[0:0] === 1'b1) ? mt10_fu_2649_p2 : r_V_62_9_cast_fu_2467_p1);

assign Eta_ans_4_V_6 = ((tmp_523_9_fu_2505_p2[0:0] === 1'b1) ? mt8_fu_2669_p2 : r_V_63_9_cast_fu_2495_p1);

assign Eta_ans_4_V_7 = ((tmp_525_9_fu_2527_p2[0:0] === 1'b1) ? mt6_fu_2689_p2 : r_V_64_9_cast_fu_2523_p1);

assign Eta_ans_4_V_8 = ((tmp_527_9_fu_2543_p2[0:0] === 1'b1) ? mt4_fu_2709_p2 : r_V_65_9_cast_fu_2539_p1);

assign Eta_ans_4_V_9 = ((tmp_529_8_fu_2072_p2[0:0] === 1'b1) ? mt_fu_2729_p2 : r_V_66_8_cast_fu_2068_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_0];

assign ap_enable_reg_pp0_iter0 = ap_start;

assign mt10_fu_2649_p2 = (ap_const_lv8_0 - r_V_62_9_cast_fu_2467_p1);

assign mt11_fu_2549_p2 = (ap_const_lv8_0 - r_V_57_9_cast_fu_2230_p1);

assign mt12_fu_2629_p2 = (ap_const_lv8_0 - r_V_61_9_cast_fu_2433_p1);

assign mt13_fu_2569_p2 = (ap_const_lv8_0 - r_V_58_9_cast_fu_2290_p1);

assign mt14_fu_2609_p2 = (ap_const_lv8_0 - r_V_60_9_cast_fu_2399_p1);

assign mt15_fu_2589_p2 = (ap_const_lv8_0 - r_V_59_9_cast_fu_2327_p1);

assign mt4_fu_2709_p2 = (ap_const_lv8_0 - r_V_65_9_cast_fu_2539_p1);

assign mt6_fu_2689_p2 = (ap_const_lv8_0 - r_V_64_9_cast_fu_2523_p1);

assign mt8_fu_2669_p2 = (ap_const_lv8_0 - r_V_63_9_cast_fu_2495_p1);

assign mt_fu_2729_p2 = (ap_const_lv8_0 - r_V_66_8_cast_fu_2068_p1);

assign p_21_cast_cast_fu_207_p3 = ((tmp_295_fu_171_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_61_1_cast_fu_330_p1 = $signed(p_61_1_fu_323_p3);

assign p_61_1_fu_323_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_1);

assign p_61_2_cast_fu_535_p1 = $signed(p_61_2_fu_528_p3);

assign p_61_2_fu_528_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_2);

assign p_61_3_cast_fu_734_p1 = $signed(p_61_3_fu_727_p3);

assign p_61_3_fu_727_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_3);

assign p_61_4_cast_fu_933_p1 = $signed(p_61_4_fu_926_p3);

assign p_61_4_fu_926_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_4);

assign p_61_5_cast_fu_1032_p1 = $signed(p_61_5_fu_1025_p3);

assign p_61_5_fu_1025_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_5);

assign p_61_6_cast_fu_1119_p1 = $signed(p_61_6_fu_1112_p3);

assign p_61_6_fu_1112_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_6);

assign p_61_7_cast_fu_1206_p1 = $signed(p_61_7_fu_1199_p3);

assign p_61_7_fu_1199_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_7);

assign p_61_8_cast_fu_1293_p1 = $signed(p_61_8_fu_1286_p3);

assign p_61_8_fu_1286_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_8);

assign p_61_9_cast_fu_1380_p1 = $signed(p_61_9_fu_1373_p3);

assign p_61_9_fu_1373_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_9);

assign p_62_1_cast_cast_fu_406_p3 = ((tmp_504_1_fu_370_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_2_cast_cast_fu_611_p3 = ((tmp_504_2_fu_575_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_3_cast_cast_fu_810_p3 = ((tmp_504_3_fu_774_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_4_cast_cast_fu_1496_p3 = ((tmp_504_4_reg_2824[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_5_cast_cast_fu_1603_p3 = ((tmp_504_5_reg_2869[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_6_cast_cast_fu_1722_p3 = ((tmp_504_6_reg_2910[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_7_cast_cast_fu_1841_p3 = ((tmp_504_7_reg_2950[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_8_cast_cast_fu_1960_p3 = ((tmp_504_8_reg_2990[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_62_9_cast_cast_fu_2083_p3 = ((tmp_504_9_reg_3030[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_3);

assign p_cast_fu_131_p1 = $signed(p_s_fu_124_p3);

assign p_s_fu_124_p3 = ((tmp_reg_2749[0:0] === 1'b1) ? ap_const_lv8_0 : Peta_tabf_V_0);

assign r_V_57_9_cast_fu_2230_p1 = r_V_57_9_fu_2224_p2;

assign r_V_57_9_fu_2224_p2 = (tmp285_fu_2218_p2 & tmp281_fu_2197_p2);

assign r_V_58_9_cast_fu_2290_p1 = r_V_58_9_fu_2284_p2;

assign r_V_58_9_fu_2284_p2 = (tmp294_fu_2278_p2 & tmp281_fu_2197_p2);

assign r_V_59_1_fu_518_p2 = (rhs_V_s_fu_311_p3 & rhs_V_10_1_fu_510_p3);

assign r_V_59_9_cast_fu_2327_p1 = r_V_59_9_fu_2321_p2;

assign r_V_59_9_fu_2321_p2 = (tmp298_fu_2315_p2 & tmp281_fu_2197_p2);

assign r_V_60_2_fu_1465_p2 = (r_V_59_1_reg_2785 & rhs_V_10_2_reg_2798);

assign r_V_60_9_cast_fu_2399_p1 = r_V_60_9_fu_2393_p2;

assign r_V_60_9_fu_2393_p2 = (tmp308_fu_2387_p2 & tmp305_fu_2369_p2);

assign r_V_61_3_fu_1480_p2 = (r_V_60_2_fu_1465_p2 & rhs_V_10_3_reg_2811);

assign r_V_61_9_cast_fu_2433_p1 = r_V_61_9_fu_2427_p2;

assign r_V_61_9_fu_2427_p2 = (tmp311_fu_2421_p2 & tmp305_fu_2369_p2);

assign r_V_62_4_fu_1586_p2 = (r_V_61_3_fu_1480_p2 & rhs_V_10_4_fu_1578_p3);

assign r_V_62_9_cast_fu_2467_p1 = r_V_62_9_fu_2461_p2;

assign r_V_62_9_fu_2461_p2 = (tmp314_fu_2455_p2 & tmp279_fu_2185_p2);

assign r_V_63_5_fu_1705_p2 = (r_V_62_4_fu_1586_p2 & rhs_V_10_5_fu_1697_p3);

assign r_V_63_9_cast_fu_2495_p1 = r_V_63_9_fu_2489_p2;

assign r_V_63_9_fu_2489_p2 = (tmp316_fu_2483_p2 & tmp279_fu_2185_p2);

assign r_V_64_6_fu_1824_p2 = (r_V_63_5_fu_1705_p2 & rhs_V_10_6_fu_1816_p3);

assign r_V_64_9_cast_fu_2523_p1 = r_V_64_9_fu_2517_p2;

assign r_V_64_9_fu_2517_p2 = (tmp318_fu_2511_p2 & r_V_64_6_fu_1824_p2);

assign r_V_65_7_fu_1943_p2 = (r_V_64_6_fu_1824_p2 & rhs_V_10_7_fu_1935_p3);

assign r_V_65_9_cast_fu_2539_p1 = r_V_65_9_fu_2533_p2;

assign r_V_65_9_fu_2533_p2 = (r_V_65_7_fu_1943_p2 & rhs_V_10_9_fu_2177_p3);

assign r_V_66_8_cast_fu_2068_p1 = r_V_66_8_fu_2062_p2;

assign r_V_66_8_fu_2062_p2 = (r_V_65_7_fu_1943_p2 & rhs_V_10_8_fu_2054_p3);

assign rev10_fu_1475_p2 = (tmp_337_reg_2805 ^ 1'b1);

assign rev13_fu_1491_p2 = (tmp_338_reg_2817 ^ 1'b1);

assign rev16_fu_1598_p2 = (tmp_339_reg_2862 ^ 1'b1);

assign rev19_fu_1717_p2 = (tmp_340_reg_2903 ^ 1'b1);

assign rev22_fu_1836_p2 = (tmp_341_reg_2944 ^ 1'b1);

assign rev23_fu_2078_p2 = (tmp_343_reg_3024 ^ 1'b1);

assign rev7_fu_1460_p2 = (tmp_336_reg_2791 ^ 1'b1);

assign rev_fu_1955_p2 = (tmp_342_reg_2984 ^ 1'b1);

assign rhs_V_10_1_fu_510_p3 = ((tmp_317_fu_504_p2[0:0] === 1'b1) ? sel_tmp41_cast_fu_496_p3 : sel_tmp34_fu_464_p3);

assign rhs_V_10_2_fu_715_p3 = ((tmp_319_fu_709_p2[0:0] === 1'b1) ? sel_tmp67_cast_fu_701_p3 : sel_tmp60_fu_669_p3);

assign rhs_V_10_3_fu_914_p3 = ((tmp_321_fu_908_p2[0:0] === 1'b1) ? sel_tmp93_cast_fu_900_p3 : sel_tmp86_fu_868_p3);

assign rhs_V_10_4_fu_1578_p3 = ((tmp_323_fu_1572_p2[0:0] === 1'b1) ? sel_tmp119_cast_fu_1564_p3 : sel_tmp112_fu_1536_p3);

assign rhs_V_10_5_fu_1697_p3 = ((tmp_325_fu_1691_p2[0:0] === 1'b1) ? sel_tmp145_cast_fu_1683_p3 : sel_tmp138_fu_1655_p3);

assign rhs_V_10_6_fu_1816_p3 = ((tmp_327_fu_1810_p2[0:0] === 1'b1) ? sel_tmp171_cast_fu_1802_p3 : sel_tmp164_fu_1774_p3);

assign rhs_V_10_7_fu_1935_p3 = ((tmp_329_fu_1929_p2[0:0] === 1'b1) ? sel_tmp197_cast_fu_1921_p3 : sel_tmp190_fu_1893_p3);

assign rhs_V_10_8_fu_2054_p3 = ((tmp_331_fu_2048_p2[0:0] === 1'b1) ? sel_tmp223_cast_fu_2040_p3 : sel_tmp216_fu_2012_p3);

assign rhs_V_10_9_fu_2177_p3 = ((tmp_333_fu_2171_p2[0:0] === 1'b1) ? sel_tmp249_cast_fu_2163_p3 : sel_tmp239_fu_2135_p3);

assign rhs_V_1_fu_338_p1 = $signed(Lam_tabf_V_1);

assign rhs_V_2_fu_543_p1 = $signed(Lam_tabf_V_2);

assign rhs_V_3_fu_742_p1 = $signed(Lam_tabf_V_3);

assign rhs_V_4_fu_941_p1 = $signed(Lam_tabf_V_4);

assign rhs_V_5_fu_1040_p1 = $signed(Lam_tabf_V_5);

assign rhs_V_6_fu_1127_p1 = $signed(Lam_tabf_V_6);

assign rhs_V_7_fu_1214_p1 = $signed(Lam_tabf_V_7);

assign rhs_V_8_fu_1301_p1 = $signed(Lam_tabf_V_8);

assign rhs_V_9_fu_1388_p1 = $signed(Lam_tabf_V_9);

assign rhs_V_fu_139_p1 = $signed(Lam_tabf_V_0);

assign rhs_V_s_fu_311_p3 = ((tmp_315_fu_305_p2[0:0] === 1'b1) ? sel_tmp15_cast_fu_297_p3 : sel_tmp8_fu_265_p3);

assign sel_tmp100_fu_888_p2 = (tmp_507_3_fu_792_p2 ^ 1'b1);

assign sel_tmp101_fu_894_p2 = (tmp_508_3_fu_798_p2 & sel_tmp100_fu_888_p2);

assign sel_tmp104_cast_fu_1510_p1 = $signed(sel_tmp104_fu_1503_p3);

assign sel_tmp104_fu_1503_p3 = ((tmp_509_4_reg_2851[0:0] === 1'b1) ? p_62_4_cast_cast_fu_1496_p3 : ap_const_lv3_1);

assign sel_tmp105_fu_1514_p2 = (tmp_504_4_reg_2824 ^ 1'b1);

assign sel_tmp106_fu_1519_p2 = (tmp_505_4_reg_2830 & sel_tmp105_fu_1514_p2);

assign sel_tmp107_cast_fu_1524_p3 = ((sel_tmp111_reg_2856[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp110_fu_1009_p2 = (tmp_505_4_fu_979_p2 ^ 1'b1);

assign sel_tmp111_fu_1015_p2 = (tmp_506_4_fu_985_p2 & sel_tmp110_fu_1009_p2);

assign sel_tmp112_fu_1536_p3 = ((tmp_322_fu_1531_p2[0:0] === 1'b1) ? sel_tmp107_cast_fu_1524_p3 : sel_tmp104_cast_fu_1510_p1);

assign sel_tmp117_fu_1544_p2 = (tmp_506_4_reg_2835 ^ 1'b1);

assign sel_tmp118_fu_1549_p2 = (tmp_507_4_reg_2840 & sel_tmp117_fu_1544_p2);

assign sel_tmp119_cast_fu_1564_p3 = ((sel_tmp127_fu_1559_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp126_fu_1554_p2 = (tmp_507_4_reg_2840 ^ 1'b1);

assign sel_tmp127_fu_1559_p2 = (tmp_508_4_reg_2846 & sel_tmp126_fu_1554_p2);

assign sel_tmp130_cast_fu_1617_p1 = $signed(sel_tmp130_fu_1610_p3);

assign sel_tmp130_fu_1610_p3 = ((tmp_509_5_reg_2898[0:0] === 1'b1) ? p_62_5_cast_cast_fu_1603_p3 : ap_const_lv3_1);

assign sel_tmp131_fu_1621_p2 = (tmp_504_5_reg_2869 ^ 1'b1);

assign sel_tmp132_fu_1626_p2 = (tmp_505_5_reg_2875 & sel_tmp131_fu_1621_p2);

assign sel_tmp133_cast_fu_1641_p3 = ((sel_tmp137_fu_1636_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp136_fu_1631_p2 = (tmp_505_5_reg_2875 ^ 1'b1);

assign sel_tmp137_fu_1636_p2 = (tmp_506_5_reg_2881 & sel_tmp136_fu_1631_p2);

assign sel_tmp138_fu_1655_p3 = ((tmp_324_fu_1649_p2[0:0] === 1'b1) ? sel_tmp133_cast_fu_1641_p3 : sel_tmp130_cast_fu_1617_p1);

assign sel_tmp13_fu_273_p2 = (tmp_297_fu_183_p2 ^ 1'b1);

assign sel_tmp143_fu_1663_p2 = (tmp_506_5_reg_2881 ^ 1'b1);

assign sel_tmp144_fu_1668_p2 = (tmp_507_5_reg_2887 & sel_tmp143_fu_1663_p2);

assign sel_tmp145_cast_fu_1683_p3 = ((sel_tmp153_fu_1678_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp14_fu_279_p2 = (tmp_298_fu_189_p2 & sel_tmp13_fu_273_p2);

assign sel_tmp152_fu_1673_p2 = (tmp_507_5_reg_2887 ^ 1'b1);

assign sel_tmp153_fu_1678_p2 = (tmp_508_5_reg_2893 & sel_tmp152_fu_1673_p2);

assign sel_tmp156_cast_fu_1736_p1 = $signed(sel_tmp156_fu_1729_p3);

assign sel_tmp156_fu_1729_p3 = ((tmp_509_6_reg_2939[0:0] === 1'b1) ? p_62_6_cast_cast_fu_1722_p3 : ap_const_lv3_1);

assign sel_tmp157_fu_1740_p2 = (tmp_504_6_reg_2910 ^ 1'b1);

assign sel_tmp158_fu_1745_p2 = (tmp_505_6_reg_2916 & sel_tmp157_fu_1740_p2);

assign sel_tmp159_cast_fu_1760_p3 = ((sel_tmp163_fu_1755_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp15_cast_fu_297_p3 = ((sel_tmp23_fu_291_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp162_fu_1750_p2 = (tmp_505_6_reg_2916 ^ 1'b1);

assign sel_tmp163_fu_1755_p2 = (tmp_506_6_reg_2922 & sel_tmp162_fu_1750_p2);

assign sel_tmp164_fu_1774_p3 = ((tmp_326_fu_1768_p2[0:0] === 1'b1) ? sel_tmp159_cast_fu_1760_p3 : sel_tmp156_cast_fu_1736_p1);

assign sel_tmp169_fu_1782_p2 = (tmp_506_6_reg_2922 ^ 1'b1);

assign sel_tmp170_fu_1787_p2 = (tmp_507_6_reg_2928 & sel_tmp169_fu_1782_p2);

assign sel_tmp171_cast_fu_1802_p3 = ((sel_tmp179_fu_1797_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp178_fu_1792_p2 = (tmp_507_6_reg_2928 ^ 1'b1);

assign sel_tmp179_fu_1797_p2 = (tmp_508_6_reg_2934 & sel_tmp178_fu_1792_p2);

assign sel_tmp182_cast_fu_1855_p1 = $signed(sel_tmp182_fu_1848_p3);

assign sel_tmp182_fu_1848_p3 = ((tmp_509_7_reg_2979[0:0] === 1'b1) ? p_62_7_cast_cast_fu_1841_p3 : ap_const_lv3_1);

assign sel_tmp183_fu_1859_p2 = (tmp_504_7_reg_2950 ^ 1'b1);

assign sel_tmp184_fu_1864_p2 = (tmp_505_7_reg_2956 & sel_tmp183_fu_1859_p2);

assign sel_tmp185_cast_fu_1879_p3 = ((sel_tmp189_fu_1874_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp188_fu_1869_p2 = (tmp_505_7_reg_2956 ^ 1'b1);

assign sel_tmp189_fu_1874_p2 = (tmp_506_7_reg_2962 & sel_tmp188_fu_1869_p2);

assign sel_tmp190_fu_1893_p3 = ((tmp_328_fu_1887_p2[0:0] === 1'b1) ? sel_tmp185_cast_fu_1879_p3 : sel_tmp182_cast_fu_1855_p1);

assign sel_tmp195_fu_1901_p2 = (tmp_506_7_reg_2962 ^ 1'b1);

assign sel_tmp196_fu_1906_p2 = (tmp_507_7_reg_2968 & sel_tmp195_fu_1901_p2);

assign sel_tmp197_cast_fu_1921_p3 = ((sel_tmp205_fu_1916_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp1_fu_227_p2 = (tmp_295_fu_171_p2 ^ 1'b1);

assign sel_tmp204_fu_1911_p2 = (tmp_507_7_reg_2968 ^ 1'b1);

assign sel_tmp205_fu_1916_p2 = (tmp_508_7_reg_2974 & sel_tmp204_fu_1911_p2);

assign sel_tmp208_cast_fu_1974_p1 = $signed(sel_tmp208_fu_1967_p3);

assign sel_tmp208_fu_1967_p3 = ((tmp_509_8_reg_3019[0:0] === 1'b1) ? p_62_8_cast_cast_fu_1960_p3 : ap_const_lv3_1);

assign sel_tmp209_fu_1978_p2 = (tmp_504_8_reg_2990 ^ 1'b1);

assign sel_tmp210_fu_1983_p2 = (tmp_505_8_reg_2996 & sel_tmp209_fu_1978_p2);

assign sel_tmp211_cast_fu_1998_p3 = ((sel_tmp215_fu_1993_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp214_fu_1988_p2 = (tmp_505_8_reg_2996 ^ 1'b1);

assign sel_tmp215_fu_1993_p2 = (tmp_506_8_reg_3002 & sel_tmp214_fu_1988_p2);

assign sel_tmp216_fu_2012_p3 = ((tmp_330_fu_2006_p2[0:0] === 1'b1) ? sel_tmp211_cast_fu_1998_p3 : sel_tmp208_cast_fu_1974_p1);

assign sel_tmp221_fu_2020_p2 = (tmp_506_8_reg_3002 ^ 1'b1);

assign sel_tmp222_fu_2025_p2 = (tmp_507_8_reg_3008 & sel_tmp221_fu_2020_p2);

assign sel_tmp223_cast_fu_2040_p3 = ((sel_tmp231_fu_2035_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp22_fu_285_p2 = (tmp_298_fu_189_p2 ^ 1'b1);

assign sel_tmp230_fu_2030_p2 = (tmp_507_8_reg_3008 ^ 1'b1);

assign sel_tmp231_fu_2035_p2 = (tmp_508_8_reg_3014 & sel_tmp230_fu_2030_p2);

assign sel_tmp234_cast_fu_2097_p1 = $signed(sel_tmp234_fu_2090_p3);

assign sel_tmp234_fu_2090_p3 = ((tmp_509_9_reg_3059[0:0] === 1'b1) ? p_62_9_cast_cast_fu_2083_p3 : ap_const_lv3_1);

assign sel_tmp235_fu_2101_p2 = (tmp_504_9_reg_3030 ^ 1'b1);

assign sel_tmp236_fu_2106_p2 = (tmp_505_9_reg_3036 & sel_tmp235_fu_2101_p2);

assign sel_tmp237_cast_fu_2121_p3 = ((sel_tmp238_fu_2116_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp237_fu_2111_p2 = (tmp_505_9_reg_3036 ^ 1'b1);

assign sel_tmp238_fu_2116_p2 = (tmp_506_9_reg_3042 & sel_tmp237_fu_2111_p2);

assign sel_tmp239_fu_2135_p3 = ((tmp_332_fu_2129_p2[0:0] === 1'b1) ? sel_tmp237_cast_fu_2121_p3 : sel_tmp234_cast_fu_2097_p1);

assign sel_tmp23_fu_291_p2 = (tmp_299_fu_195_p2 & sel_tmp22_fu_285_p2);

assign sel_tmp240_fu_2143_p2 = (tmp_506_9_reg_3042 ^ 1'b1);

assign sel_tmp241_fu_2148_p2 = (tmp_507_9_reg_3048 & sel_tmp240_fu_2143_p2);

assign sel_tmp242_fu_2153_p2 = (tmp_507_9_reg_3048 ^ 1'b1);

assign sel_tmp243_fu_2158_p2 = (tmp_508_9_reg_3054 & sel_tmp242_fu_2153_p2);

assign sel_tmp249_cast_fu_2163_p3 = ((sel_tmp243_fu_2158_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp26_cast_fu_422_p1 = $signed(sel_tmp26_fu_414_p3);

assign sel_tmp26_fu_414_p3 = ((tmp_509_1_fu_400_p2[0:0] === 1'b1) ? p_62_1_cast_cast_fu_406_p3 : ap_const_lv3_1);

assign sel_tmp27_fu_426_p2 = (tmp_504_1_fu_370_p2 ^ 1'b1);

assign sel_tmp28_fu_432_p2 = (tmp_505_1_fu_376_p2 & sel_tmp27_fu_426_p2);

assign sel_tmp29_cast_fu_450_p3 = ((sel_tmp33_fu_444_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp2_fu_233_p2 = (tmp_296_fu_177_p2 & sel_tmp1_fu_227_p2);

assign sel_tmp32_fu_438_p2 = (tmp_505_1_fu_376_p2 ^ 1'b1);

assign sel_tmp33_fu_444_p2 = (tmp_506_1_fu_382_p2 & sel_tmp32_fu_438_p2);

assign sel_tmp34_fu_464_p3 = ((tmp_316_fu_458_p2[0:0] === 1'b1) ? sel_tmp29_cast_fu_450_p3 : sel_tmp26_cast_fu_422_p1);

assign sel_tmp39_fu_472_p2 = (tmp_506_1_fu_382_p2 ^ 1'b1);

assign sel_tmp3_cast_fu_251_p3 = ((sel_tmp7_fu_245_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp40_fu_478_p2 = (tmp_507_1_fu_388_p2 & sel_tmp39_fu_472_p2);

assign sel_tmp41_cast_fu_496_p3 = ((sel_tmp49_fu_490_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp48_fu_484_p2 = (tmp_507_1_fu_388_p2 ^ 1'b1);

assign sel_tmp49_fu_490_p2 = (tmp_508_1_fu_394_p2 & sel_tmp48_fu_484_p2);

assign sel_tmp52_cast_fu_627_p1 = $signed(sel_tmp52_fu_619_p3);

assign sel_tmp52_fu_619_p3 = ((tmp_509_2_fu_605_p2[0:0] === 1'b1) ? p_62_2_cast_cast_fu_611_p3 : ap_const_lv3_1);

assign sel_tmp53_fu_631_p2 = (tmp_504_2_fu_575_p2 ^ 1'b1);

assign sel_tmp54_fu_637_p2 = (tmp_505_2_fu_581_p2 & sel_tmp53_fu_631_p2);

assign sel_tmp55_cast_fu_655_p3 = ((sel_tmp59_fu_649_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp58_fu_643_p2 = (tmp_505_2_fu_581_p2 ^ 1'b1);

assign sel_tmp59_fu_649_p2 = (tmp_506_2_fu_587_p2 & sel_tmp58_fu_643_p2);

assign sel_tmp60_fu_669_p3 = ((tmp_318_fu_663_p2[0:0] === 1'b1) ? sel_tmp55_cast_fu_655_p3 : sel_tmp52_cast_fu_627_p1);

assign sel_tmp65_fu_677_p2 = (tmp_506_2_fu_587_p2 ^ 1'b1);

assign sel_tmp66_fu_683_p2 = (tmp_507_2_fu_593_p2 & sel_tmp65_fu_677_p2);

assign sel_tmp67_cast_fu_701_p3 = ((sel_tmp75_fu_695_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp6_fu_239_p2 = (tmp_296_fu_177_p2 ^ 1'b1);

assign sel_tmp74_fu_689_p2 = (tmp_507_2_fu_593_p2 ^ 1'b1);

assign sel_tmp75_fu_695_p2 = (tmp_508_2_fu_599_p2 & sel_tmp74_fu_689_p2);

assign sel_tmp78_cast_fu_826_p1 = $signed(sel_tmp78_fu_818_p3);

assign sel_tmp78_fu_818_p3 = ((tmp_509_3_fu_804_p2[0:0] === 1'b1) ? p_62_3_cast_cast_fu_810_p3 : ap_const_lv3_1);

assign sel_tmp79_fu_830_p2 = (tmp_504_3_fu_774_p2 ^ 1'b1);

assign sel_tmp7_fu_245_p2 = (tmp_297_fu_183_p2 & sel_tmp6_fu_239_p2);

assign sel_tmp80_fu_836_p2 = (tmp_505_3_fu_780_p2 & sel_tmp79_fu_830_p2);

assign sel_tmp81_cast_fu_854_p3 = ((sel_tmp85_fu_848_p2[0:0] === 1'b1) ? ap_const_lv7_1F : ap_const_lv7_3F);

assign sel_tmp84_fu_842_p2 = (tmp_505_3_fu_780_p2 ^ 1'b1);

assign sel_tmp85_fu_848_p2 = (tmp_506_3_fu_786_p2 & sel_tmp84_fu_842_p2);

assign sel_tmp86_fu_868_p3 = ((tmp_320_fu_862_p2[0:0] === 1'b1) ? sel_tmp81_cast_fu_854_p3 : sel_tmp78_cast_fu_826_p1);

assign sel_tmp8_fu_265_p3 = ((tmp_314_fu_259_p2[0:0] === 1'b1) ? sel_tmp3_cast_fu_251_p3 : sel_tmp_cast_fu_223_p1);

assign sel_tmp91_fu_876_p2 = (tmp_506_3_fu_786_p2 ^ 1'b1);

assign sel_tmp92_fu_882_p2 = (tmp_507_3_fu_792_p2 & sel_tmp91_fu_876_p2);

assign sel_tmp93_cast_fu_900_p3 = ((sel_tmp101_fu_894_p2[0:0] === 1'b1) ? ap_const_lv7_7 : ap_const_lv7_F);

assign sel_tmp_cast_fu_223_p1 = $signed(sel_tmp_fu_215_p3);

assign sel_tmp_fu_215_p3 = ((tmp_300_fu_201_p2[0:0] === 1'b1) ? p_21_cast_cast_fu_207_p3 : ap_const_lv3_1);

assign tmp279_fu_2185_p2 = (rhs_V_10_7_fu_1935_p3 & rhs_V_10_8_fu_2054_p3);

assign tmp280_fu_2191_p2 = (rhs_V_10_6_fu_1816_p3 & rhs_V_10_5_fu_1697_p3);

assign tmp281_fu_2197_p2 = (tmp280_fu_2191_p2 & tmp279_fu_2185_p2);

assign tmp282_fu_2203_p2 = (rhs_V_10_2_reg_2798 & rhs_V_10_1_reg_2780);

assign tmp283_fu_2207_p2 = (rhs_V_10_3_reg_2811 & rhs_V_10_9_fu_2177_p3);

assign tmp284_fu_2212_p2 = (tmp283_fu_2207_p2 & rhs_V_10_4_fu_1578_p3);

assign tmp285_fu_2218_p2 = (tmp284_fu_2212_p2 & tmp282_fu_2203_p2);

assign tmp286_fu_2234_p2 = (tmp_335_reg_2774 ^ tmp_336_reg_2791);

assign tmp287_fu_2238_p2 = (tmp_337_reg_2805 ^ tmp_338_reg_2817);

assign tmp288_fu_2242_p2 = (tmp287_fu_2238_p2 ^ tmp286_fu_2234_p2);

assign tmp289_fu_2248_p2 = (tmp_339_reg_2862 ^ tmp_340_reg_2903);

assign tmp290_fu_2252_p2 = (tmp_342_reg_2984 ^ tmp_343_reg_3024);

assign tmp291_fu_2256_p2 = (tmp290_fu_2252_p2 ^ rev22_fu_1836_p2);

assign tmp292_fu_2262_p2 = (tmp291_fu_2256_p2 ^ tmp289_fu_2248_p2);

assign tmp293_fu_2274_p2 = (rhs_V_10_2_reg_2798 & rhs_V_s_reg_2769);

assign tmp294_fu_2278_p2 = (tmp284_fu_2212_p2 & tmp293_fu_2274_p2);

assign tmp295_fu_2294_p2 = (tmp_334_reg_2763 ^ tmp_336_reg_2791);

assign tmp296_fu_2298_p2 = (tmp287_fu_2238_p2 ^ tmp295_fu_2294_p2);

assign tmp297_fu_2310_p2 = (r_V_59_1_reg_2785 & rhs_V_10_4_fu_1578_p3);

assign tmp298_fu_2315_p2 = (tmp283_fu_2207_p2 & tmp297_fu_2310_p2);

assign tmp299_fu_2331_p2 = (tmp_515_1_fu_1456_p2 ^ rev10_fu_1475_p2);

assign tmp300_fu_2337_p2 = (tmp_338_reg_2817 ^ tmp_339_reg_2862);

assign tmp301_fu_2341_p2 = (tmp300_fu_2337_p2 ^ tmp299_fu_2331_p2);

assign tmp302_fu_2347_p2 = (tmp_340_reg_2903 ^ tmp_341_reg_2944);

assign tmp303_fu_2351_p2 = (tmp290_fu_2252_p2 ^ tmp302_fu_2347_p2);

assign tmp304_fu_2363_p2 = (rhs_V_10_8_fu_2054_p3 & rhs_V_10_6_fu_1816_p3);

assign tmp305_fu_2369_p2 = (tmp304_fu_2363_p2 & rhs_V_10_7_fu_1935_p3);

assign tmp306_fu_2375_p2 = (r_V_60_2_fu_1465_p2 & rhs_V_10_5_fu_1697_p3);

assign tmp307_fu_2381_p2 = (rhs_V_10_4_fu_1578_p3 & rhs_V_10_9_fu_2177_p3);

assign tmp308_fu_2387_p2 = (tmp307_fu_2381_p2 & tmp306_fu_2375_p2);

assign tmp309_fu_2403_p2 = (tmp300_fu_2337_p2 ^ tmp_517_2_fu_1469_p2);

assign tmp310_fu_2415_p2 = (r_V_61_3_fu_1480_p2 & rhs_V_10_9_fu_2177_p3);

assign tmp311_fu_2421_p2 = (tmp310_fu_2415_p2 & rhs_V_10_5_fu_1697_p3);

assign tmp312_fu_2437_p2 = (tmp289_fu_2248_p2 ^ tmp_519_3_fu_1485_p2);

assign tmp313_fu_2449_p2 = (r_V_62_4_fu_1586_p2 & rhs_V_10_9_fu_2177_p3);

assign tmp314_fu_2455_p2 = (tmp313_fu_2449_p2 & rhs_V_10_6_fu_1816_p3);

assign tmp315_fu_2471_p2 = (tmp_521_4_fu_1592_p2 ^ rev19_fu_1717_p2);

assign tmp316_fu_2483_p2 = (r_V_63_5_fu_1705_p2 & rhs_V_10_9_fu_2177_p3);

assign tmp317_fu_2499_p2 = (tmp_523_5_fu_1711_p2 ^ rev22_fu_1836_p2);

assign tmp318_fu_2511_p2 = (rhs_V_10_8_fu_2054_p3 & rhs_V_10_9_fu_2177_p3);

assign tmp_295_fu_171_p2 = (($signed(vArg_V_s_fu_163_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_296_fu_177_p2 = (($signed(vArg_V_s_fu_163_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_297_fu_183_p2 = (($signed(vArg_V_s_fu_163_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_298_fu_189_p2 = (($signed(vArg_V_s_fu_163_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_299_fu_195_p2 = (($signed(vArg_V_s_fu_163_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_300_fu_201_p2 = (($signed(vArg_V_s_fu_163_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_314_fu_259_p2 = (sel_tmp7_fu_245_p2 | sel_tmp2_fu_233_p2);

assign tmp_315_fu_305_p2 = (sel_tmp23_fu_291_p2 | sel_tmp14_fu_279_p2);

assign tmp_316_fu_458_p2 = (sel_tmp33_fu_444_p2 | sel_tmp28_fu_432_p2);

assign tmp_317_fu_504_p2 = (sel_tmp49_fu_490_p2 | sel_tmp40_fu_478_p2);

assign tmp_318_fu_663_p2 = (sel_tmp59_fu_649_p2 | sel_tmp54_fu_637_p2);

assign tmp_319_fu_709_p2 = (sel_tmp75_fu_695_p2 | sel_tmp66_fu_683_p2);

assign tmp_320_fu_862_p2 = (sel_tmp85_fu_848_p2 | sel_tmp80_fu_836_p2);

assign tmp_321_fu_908_p2 = (sel_tmp101_fu_894_p2 | sel_tmp92_fu_882_p2);

assign tmp_322_fu_1531_p2 = (sel_tmp111_reg_2856 | sel_tmp106_fu_1519_p2);

assign tmp_323_fu_1572_p2 = (sel_tmp127_fu_1559_p2 | sel_tmp118_fu_1549_p2);

assign tmp_324_fu_1649_p2 = (sel_tmp137_fu_1636_p2 | sel_tmp132_fu_1626_p2);

assign tmp_325_fu_1691_p2 = (sel_tmp153_fu_1678_p2 | sel_tmp144_fu_1668_p2);

assign tmp_326_fu_1768_p2 = (sel_tmp163_fu_1755_p2 | sel_tmp158_fu_1745_p2);

assign tmp_327_fu_1810_p2 = (sel_tmp179_fu_1797_p2 | sel_tmp170_fu_1787_p2);

assign tmp_328_fu_1887_p2 = (sel_tmp189_fu_1874_p2 | sel_tmp184_fu_1864_p2);

assign tmp_329_fu_1929_p2 = (sel_tmp205_fu_1916_p2 | sel_tmp196_fu_1906_p2);

assign tmp_330_fu_2006_p2 = (sel_tmp215_fu_1993_p2 | sel_tmp210_fu_1983_p2);

assign tmp_331_fu_2048_p2 = (sel_tmp231_fu_2035_p2 | sel_tmp222_fu_2025_p2);

assign tmp_332_fu_2129_p2 = (sel_tmp238_fu_2116_p2 | sel_tmp236_fu_2106_p2);

assign tmp_333_fu_2171_p2 = (sel_tmp243_fu_2158_p2 | sel_tmp241_fu_2148_p2);

assign tmp_334_fu_149_p3 = vArg_V_fu_143_p2[ap_const_lv32_8];

assign tmp_335_fu_348_p3 = vArg_V_1_fu_342_p2[ap_const_lv32_8];

assign tmp_336_fu_553_p3 = vArg_V_2_fu_547_p2[ap_const_lv32_8];

assign tmp_337_fu_752_p3 = vArg_V_3_fu_746_p2[ap_const_lv32_8];

assign tmp_338_fu_951_p3 = vArg_V_4_fu_945_p2[ap_const_lv32_8];

assign tmp_339_fu_1050_p3 = vArg_V_5_fu_1044_p2[ap_const_lv32_8];

assign tmp_340_fu_1137_p3 = vArg_V_6_fu_1131_p2[ap_const_lv32_8];

assign tmp_341_fu_1224_p3 = vArg_V_7_fu_1218_p2[ap_const_lv32_8];

assign tmp_342_fu_1311_p3 = vArg_V_8_fu_1305_p2[ap_const_lv32_8];

assign tmp_343_fu_1398_p3 = vArg_V_9_fu_1392_p2[ap_const_lv32_8];

assign tmp_504_1_fu_370_p2 = (($signed(vArg_V_14_1_fu_362_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_2_fu_575_p2 = (($signed(vArg_V_14_2_fu_567_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_3_fu_774_p2 = (($signed(vArg_V_14_3_fu_766_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_4_fu_973_p2 = (($signed(vArg_V_14_4_fu_965_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_5_fu_1072_p2 = (($signed(vArg_V_14_5_fu_1064_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_6_fu_1159_p2 = (($signed(vArg_V_14_6_fu_1151_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_7_fu_1246_p2 = (($signed(vArg_V_14_7_fu_1238_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_8_fu_1333_p2 = (($signed(vArg_V_14_8_fu_1325_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_504_9_fu_1420_p2 = (($signed(vArg_V_14_9_fu_1412_p3) > $signed(9'b1111110)) ? 1'b1 : 1'b0);

assign tmp_505_1_fu_376_p2 = (($signed(vArg_V_14_1_fu_362_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_2_fu_581_p2 = (($signed(vArg_V_14_2_fu_567_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_3_fu_780_p2 = (($signed(vArg_V_14_3_fu_766_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_4_fu_979_p2 = (($signed(vArg_V_14_4_fu_965_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_5_fu_1078_p2 = (($signed(vArg_V_14_5_fu_1064_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_6_fu_1165_p2 = (($signed(vArg_V_14_6_fu_1151_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_7_fu_1252_p2 = (($signed(vArg_V_14_7_fu_1238_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_8_fu_1339_p2 = (($signed(vArg_V_14_8_fu_1325_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_505_9_fu_1426_p2 = (($signed(vArg_V_14_9_fu_1412_p3) > $signed(9'b111110)) ? 1'b1 : 1'b0);

assign tmp_506_1_fu_382_p2 = (($signed(vArg_V_14_1_fu_362_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_2_fu_587_p2 = (($signed(vArg_V_14_2_fu_567_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_3_fu_786_p2 = (($signed(vArg_V_14_3_fu_766_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_4_fu_985_p2 = (($signed(vArg_V_14_4_fu_965_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_5_fu_1084_p2 = (($signed(vArg_V_14_5_fu_1064_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_6_fu_1171_p2 = (($signed(vArg_V_14_6_fu_1151_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_7_fu_1258_p2 = (($signed(vArg_V_14_7_fu_1238_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_8_fu_1345_p2 = (($signed(vArg_V_14_8_fu_1325_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_506_9_fu_1432_p2 = (($signed(vArg_V_14_9_fu_1412_p3) > $signed(9'b11110)) ? 1'b1 : 1'b0);

assign tmp_507_1_fu_388_p2 = (($signed(vArg_V_14_1_fu_362_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_2_fu_593_p2 = (($signed(vArg_V_14_2_fu_567_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_3_fu_792_p2 = (($signed(vArg_V_14_3_fu_766_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_4_fu_991_p2 = (($signed(vArg_V_14_4_fu_965_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_5_fu_1090_p2 = (($signed(vArg_V_14_5_fu_1064_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_6_fu_1177_p2 = (($signed(vArg_V_14_6_fu_1151_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_7_fu_1264_p2 = (($signed(vArg_V_14_7_fu_1238_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_8_fu_1351_p2 = (($signed(vArg_V_14_8_fu_1325_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_507_9_fu_1438_p2 = (($signed(vArg_V_14_9_fu_1412_p3) > $signed(9'b1110)) ? 1'b1 : 1'b0);

assign tmp_508_1_fu_394_p2 = (($signed(vArg_V_14_1_fu_362_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_2_fu_599_p2 = (($signed(vArg_V_14_2_fu_567_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_3_fu_798_p2 = (($signed(vArg_V_14_3_fu_766_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_4_fu_997_p2 = (($signed(vArg_V_14_4_fu_965_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_5_fu_1096_p2 = (($signed(vArg_V_14_5_fu_1064_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_6_fu_1183_p2 = (($signed(vArg_V_14_6_fu_1151_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_7_fu_1270_p2 = (($signed(vArg_V_14_7_fu_1238_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_8_fu_1357_p2 = (($signed(vArg_V_14_8_fu_1325_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_508_9_fu_1444_p2 = (($signed(vArg_V_14_9_fu_1412_p3) > $signed(9'b110)) ? 1'b1 : 1'b0);

assign tmp_509_1_fu_400_p2 = (($signed(vArg_V_14_1_fu_362_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_2_fu_605_p2 = (($signed(vArg_V_14_2_fu_567_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_3_fu_804_p2 = (($signed(vArg_V_14_3_fu_766_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_4_fu_1003_p2 = (($signed(vArg_V_14_4_fu_965_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_5_fu_1102_p2 = (($signed(vArg_V_14_5_fu_1064_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_6_fu_1189_p2 = (($signed(vArg_V_14_6_fu_1151_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_7_fu_1276_p2 = (($signed(vArg_V_14_7_fu_1238_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_8_fu_1363_p2 = (($signed(vArg_V_14_8_fu_1325_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_509_9_fu_1450_p2 = (($signed(vArg_V_14_9_fu_1412_p3) > $signed(9'b10)) ? 1'b1 : 1'b0);

assign tmp_511_9_fu_2268_p2 = (tmp292_fu_2262_p2 ^ tmp288_fu_2242_p2);

assign tmp_513_9_fu_2304_p2 = (tmp292_fu_2262_p2 ^ tmp296_fu_2298_p2);

assign tmp_515_1_fu_1456_p2 = (tmp_334_reg_2763 ^ tmp_335_reg_2774);

assign tmp_515_9_fu_2357_p2 = (tmp303_fu_2351_p2 ^ tmp301_fu_2341_p2);

assign tmp_517_2_fu_1469_p2 = (tmp_515_1_fu_1456_p2 ^ rev7_fu_1460_p2);

assign tmp_517_9_fu_2409_p2 = (tmp303_fu_2351_p2 ^ tmp309_fu_2403_p2);

assign tmp_519_3_fu_1485_p2 = (tmp_517_2_fu_1469_p2 ^ rev10_fu_1475_p2);

assign tmp_519_9_fu_2443_p2 = (tmp291_fu_2256_p2 ^ tmp312_fu_2437_p2);

assign tmp_521_4_fu_1592_p2 = (tmp_519_3_fu_1485_p2 ^ rev13_fu_1491_p2);

assign tmp_521_9_fu_2477_p2 = (tmp291_fu_2256_p2 ^ tmp315_fu_2471_p2);

assign tmp_523_5_fu_1711_p2 = (tmp_521_4_fu_1592_p2 ^ rev16_fu_1598_p2);

assign tmp_523_9_fu_2505_p2 = (tmp290_fu_2252_p2 ^ tmp317_fu_2499_p2);

assign tmp_525_6_fu_1830_p2 = (tmp_523_5_fu_1711_p2 ^ rev19_fu_1717_p2);

assign tmp_525_9_fu_2527_p2 = (tmp290_fu_2252_p2 ^ tmp_525_6_fu_1830_p2);

assign tmp_527_7_fu_1949_p2 = (tmp_525_6_fu_1830_p2 ^ rev22_fu_1836_p2);

assign tmp_527_9_fu_2543_p2 = (tmp_527_7_fu_1949_p2 ^ rev23_fu_2078_p2);

assign tmp_529_8_fu_2072_p2 = (tmp_527_7_fu_1949_p2 ^ rev_fu_1955_p2);

assign tmp_fu_114_p2 = ((nIterationCounter == ap_const_lv16_0) ? 1'b1 : 1'b0);

assign vArg_V_13_1_fu_356_p2 = (ap_const_lv9_0 - vArg_V_1_fu_342_p2);

assign vArg_V_13_2_fu_561_p2 = (ap_const_lv9_0 - vArg_V_2_fu_547_p2);

assign vArg_V_13_3_fu_760_p2 = (ap_const_lv9_0 - vArg_V_3_fu_746_p2);

assign vArg_V_13_4_fu_959_p2 = (ap_const_lv9_0 - vArg_V_4_fu_945_p2);

assign vArg_V_13_5_fu_1058_p2 = (ap_const_lv9_0 - vArg_V_5_fu_1044_p2);

assign vArg_V_13_6_fu_1145_p2 = (ap_const_lv9_0 - vArg_V_6_fu_1131_p2);

assign vArg_V_13_7_fu_1232_p2 = (ap_const_lv9_0 - vArg_V_7_fu_1218_p2);

assign vArg_V_13_8_fu_1319_p2 = (ap_const_lv9_0 - vArg_V_8_fu_1305_p2);

assign vArg_V_13_9_fu_1406_p2 = (ap_const_lv9_0 - vArg_V_9_fu_1392_p2);

assign vArg_V_13_fu_157_p2 = (ap_const_lv9_0 - vArg_V_fu_143_p2);

assign vArg_V_14_1_fu_362_p3 = ((tmp_335_fu_348_p3[0:0] === 1'b1) ? vArg_V_13_1_fu_356_p2 : vArg_V_1_fu_342_p2);

assign vArg_V_14_2_fu_567_p3 = ((tmp_336_fu_553_p3[0:0] === 1'b1) ? vArg_V_13_2_fu_561_p2 : vArg_V_2_fu_547_p2);

assign vArg_V_14_3_fu_766_p3 = ((tmp_337_fu_752_p3[0:0] === 1'b1) ? vArg_V_13_3_fu_760_p2 : vArg_V_3_fu_746_p2);

assign vArg_V_14_4_fu_965_p3 = ((tmp_338_fu_951_p3[0:0] === 1'b1) ? vArg_V_13_4_fu_959_p2 : vArg_V_4_fu_945_p2);

assign vArg_V_14_5_fu_1064_p3 = ((tmp_339_fu_1050_p3[0:0] === 1'b1) ? vArg_V_13_5_fu_1058_p2 : vArg_V_5_fu_1044_p2);

assign vArg_V_14_6_fu_1151_p3 = ((tmp_340_fu_1137_p3[0:0] === 1'b1) ? vArg_V_13_6_fu_1145_p2 : vArg_V_6_fu_1131_p2);

assign vArg_V_14_7_fu_1238_p3 = ((tmp_341_fu_1224_p3[0:0] === 1'b1) ? vArg_V_13_7_fu_1232_p2 : vArg_V_7_fu_1218_p2);

assign vArg_V_14_8_fu_1325_p3 = ((tmp_342_fu_1311_p3[0:0] === 1'b1) ? vArg_V_13_8_fu_1319_p2 : vArg_V_8_fu_1305_p2);

assign vArg_V_14_9_fu_1412_p3 = ((tmp_343_fu_1398_p3[0:0] === 1'b1) ? vArg_V_13_9_fu_1406_p2 : vArg_V_9_fu_1392_p2);

assign vArg_V_1_fu_342_p2 = ($signed(p_61_1_cast_fu_330_p1) - $signed(rhs_V_1_fu_338_p1));

assign vArg_V_2_fu_547_p2 = ($signed(p_61_2_cast_fu_535_p1) - $signed(rhs_V_2_fu_543_p1));

assign vArg_V_3_fu_746_p2 = ($signed(p_61_3_cast_fu_734_p1) - $signed(rhs_V_3_fu_742_p1));

assign vArg_V_4_fu_945_p2 = ($signed(p_61_4_cast_fu_933_p1) - $signed(rhs_V_4_fu_941_p1));

assign vArg_V_5_fu_1044_p2 = ($signed(p_61_5_cast_fu_1032_p1) - $signed(rhs_V_5_fu_1040_p1));

assign vArg_V_6_fu_1131_p2 = ($signed(p_61_6_cast_fu_1119_p1) - $signed(rhs_V_6_fu_1127_p1));

assign vArg_V_7_fu_1218_p2 = ($signed(p_61_7_cast_fu_1206_p1) - $signed(rhs_V_7_fu_1214_p1));

assign vArg_V_8_fu_1305_p2 = ($signed(p_61_8_cast_fu_1293_p1) - $signed(rhs_V_8_fu_1301_p1));

assign vArg_V_9_fu_1392_p2 = ($signed(p_61_9_cast_fu_1380_p1) - $signed(rhs_V_9_fu_1388_p1));

assign vArg_V_fu_143_p2 = ($signed(p_cast_fu_131_p1) - $signed(rhs_V_fu_139_p1));

assign vArg_V_s_fu_163_p3 = ((tmp_334_fu_149_p3[0:0] === 1'b1) ? vArg_V_13_fu_157_p2 : vArg_V_fu_143_p2);

always @ (posedge ap_clk) begin
    rhs_V_s_reg_2769[0] <= 1'b1;
    rhs_V_10_1_reg_2780[0] <= 1'b1;
    r_V_59_1_reg_2785[0] <= 1'b1;
    rhs_V_10_2_reg_2798[0] <= 1'b1;
    rhs_V_10_3_reg_2811[0] <= 1'b1;
end

endmodule //mcalcF
