onerror { resume }
transcript off
add wave -noreg -vgroup "SNR"  {/PilotDet_tb/signalReal} {/PilotDet_tb/signalImag} {/PilotDet_tb/signalMagSquaredSum} {/PilotDet_tb/Noise1} {/PilotDet_tb/Noise2} {/PilotDet_tb/noise1Real} {/PilotDet_tb/noise2Real} {/PilotDet_tb/noiseMagSquaredSum} {/PilotDet_tb/noiseMagCount} {/PilotDet_tb/DataValid} {/PilotDet_tb/FrameCount} {/PilotDet_tb/Frames} {/PilotDet_tb/snr0} {/PilotDet_tb/snr1} {/PilotDet_tb/snrAvg} {/PilotDet_tb/snrAvgdB}
add wave -noreg -vgroup "PD"  {/PilotDet_tb/PD_u/ce} {/PilotDet_tb/PD_u/ValidIn} {/PilotDet_tb/Count} {/PilotDet_tb/PD_u/ReIn} {/PilotDet_tb/PD_u/ImIn} {/PilotDet_tb/PD_u/AbsCntr0} {/PilotDet_tb/PD_u/AbsCntr1} {/PilotDet_tb/PD_u/Mag0GtMag1} {/PilotDet_tb/PD_u/PilotMag} {/PilotDet_tb/PD_u/PilotPulse1x} {/PilotDet_tb/PD_u/CalcThreshold} {/PilotDet_tb/PD_u/Threshold} {/PilotDet_tb/PD_u/Peak1} {/PilotDet_tb/PD_u/Peak3} {/PilotDet_tb/PD_u/PeakPointer} {/PilotDet_tb/PD_u/GoodPilot} {/PilotDet_tb/PD_u/PilotFoundPend} {/PilotDet_tb/PD_u/PilotFound} {/PilotDet_tb/PD_u/ValidOut} {/PilotDet_tb/PD_u/StartOut} {/PilotDet_tb/PD_u/ReOut} {/PilotDet_tb/PD_u/ImOut}
add wave -noreg -vgroup "PS"  {/PilotDet_tb/StartOutPS} {/PilotDet_tb/ValidOutPS}
add wave -noreg -vgroup "BRIK2"  {/PilotDet_tb/Brik2_u/TimeEstDone} {/PilotDet_tb/Brik2_u/Tau0EstNdxTE} {/PilotDet_tb/Brik2_u/Tau1EstNdxTE} {/PilotDet_tb/Brik2_u/ChanEstDone} {/PilotDet_tb/Brik2_u/H0EstR} {/PilotDet_tb/Brik2_u/H0EstI} {/PilotDet_tb/Brik2_u/H1EstR} {/PilotDet_tb/Brik2_u/H1EstI}
add wave -noreg -vgroup "NE"  -signed2 {/PilotDet_tb/Brik2_u/NE_u/clk} {/PilotDet_tb/Brik2_u/NE_u/startIn} {/PilotDet_tb/Brik2_u/NE_u/validIn} {/PilotDet_tb/Brik2_u/NE_u/neRamState} {/PilotDet_tb/Brik2_u/NE_u/sampleWriteCount} {/PilotDet_tb/Brik2_u/NE_u/samplesCaptured} {/PilotDet_tb/Brik2_u/NE_u/neState} {/PilotDet_tb/Brik2_u/NE_u/sampleCount} {/PilotDet_tb/Brik2_u/NE_u/log10Noise} {/PilotDet_tb/Brik2_u/NE_u/log10Signal} {/PilotDet_tb/Brik2_u/NE_u/iIn} {/PilotDet_tb/Brik2_u/NE_u/iRounded} {/PilotDet_tb/Brik2_u/NE_u/qIn} {/PilotDet_tb/Brik2_u/NE_u/p0r} {/PilotDet_tb/Brik2_u/NE_u/p0i} {/PilotDet_tb/Brik2_u/NE_u/h0r} {/PilotDet_tb/Brik2_u/NE_u/h0i} {/PilotDet_tb/Brik2_u/NE_u/p1r} {/PilotDet_tb/Brik2_u/NE_u/p1i} {/PilotDet_tb/Brik2_u/NE_u/h1r} {/PilotDet_tb/Brik2_u/NE_u/h1i} {/PilotDet_tb/Brik2_u/NE_u/calcNoise} {/PilotDet_tb/Brik2_u/NE_u/pilotsValid} {/PilotDet_tb/Brik2_u/NE_u/magsValid} {/PilotDet_tb/Brik2_u/NE_u/noiseEstimatesDone} {/PilotDet_tb/Brik2_u/NE_u/iSamp} {/PilotDet_tb/Brik2_u/NE_u/qSamp} {/PilotDet_tb/Brik2_u/NE_u/signalMag} {/PilotDet_tb/Brik2_u/NE_u/signalMagSquared} {/PilotDet_tb/Brik2_u/NE_u/signalSquaredSum} {/PilotDet_tb/Brik2_u/NE_u/signalSumReal} {/PilotDet_tb/Brik2_u/NE_u/iNoise0} {/PilotDet_tb/Brik2_u/NE_u/qNoise0} {/PilotDet_tb/Brik2_u/NE_u/noise0MagSquared} {/PilotDet_tb/Brik2_u/NE_u/noise0SquaredSum} {/PilotDet_tb/Brik2_u/NE_u/noiseSum0Real} {/PilotDet_tb/Brik2_u/NE_u/iPilot0} {/PilotDet_tb/Brik2_u/NE_u/qPilot0} {/PilotDet_tb/Brik2_u/NE_u/iPilot1} {/PilotDet_tb/Brik2_u/NE_u/iPilot2} {/PilotDet_tb/Brik2_u/NE_u/iNoise1} {/PilotDet_tb/Brik2_u/NE_u/iNoise2} {/PilotDet_tb/Brik2_u/NE_u/qPilot1} {/PilotDet_tb/Brik2_u/NE_u/qPilot2} {/PilotDet_tb/Brik2_u/NE_u/noise1MagSquared} {/PilotDet_tb/Brik2_u/NE_u/noise1SquaredSum} {/PilotDet_tb/Brik2_u/NE_u/noiseSum1Real} {/PilotDet_tb/Brik2_u/NE_u/noise2MagSquared} {/PilotDet_tb/Brik2_u/NE_u/noise2SquaredSum} {/PilotDet_tb/Brik2_u/NE_u/noiseSum2Real} {/PilotDet_tb/Brik2_u/NE_u/noiseSquaredSum} {/PilotDet_tb/Brik2_u/NE_u/log10MSE}
cursor "Cursor 1" 0ps  
transcript on
