onerror {resume}
radix define sfix8 -fixed -fraction 8 -signed -base signed -precision 6
radix define sfix5 -fixed -fraction 5 -signed -base signed -precision 6
radix define sfix15 -fixed -fraction 15 -signed -base signed -precision 6
radix define sfix12 -fixed -fraction 12 -signed -base signed -precision 6
radix define sfix11 -fixed -fraction 11 -signed -base signed -precision 6
quietly WaveActivateNextPane {} 0
add wave -noupdate /turbo_tb/TurboDecTop/SyncIn
add wave -noupdate /turbo_tb/TurboDecTop/ValidIn
add wave -noupdate /turbo_tb/TurboDecTop/eCA
add wave -noupdate /turbo_tb/TurboDecTop/eCB
add wave -noupdate -divider Init
add wave -noupdate -radix unsigned /turbo_tb/TurboDecTop/FrameCntr
add wave -noupdate /turbo_tb/TurboDecTop/FrameFull
add wave -noupdate -radix unsigned -radixshowbase 0 /turbo_tb/TurboDecTop/DT_Addr
add wave -noupdate -radix unsigned -radixshowbase 0 /turbo_tb/TurboDecTop/DT_Data
add wave -noupdate -radix unsigned -radixshowbase 0 /turbo_tb/TurboDecTop/IT_Addr
add wave -noupdate -radix unsigned -radixshowbase 0 /turbo_tb/TurboDecTop/IT_Data
add wave -noupdate -radix unsigned /turbo_tb/TurboDecTop/IterationCntr
add wave -noupdate -radix sfixed -childformat {{/turbo_tb/TurboDecTop/PCIA(0) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(1) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(2) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(3) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(4) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(5) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(6) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(7) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(8) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(9) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(10) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(11) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(12) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(13) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(14) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA(15) -radix sfixed}} -subitemconfig {/turbo_tb/TurboDecTop/PCIA(0) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(3) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(4) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(5) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(6) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(7) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(8) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(9) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(10) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(11) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(12) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(13) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(14) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA(15) {-height 15 -radix sfixed}} /turbo_tb/TurboDecTop/PCIA
add wave -noupdate -radix sfixed /turbo_tb/TurboDecTop/PCIB
add wave -noupdate -radix sfixed -childformat {{/turbo_tb/TurboDecTop/PCIA_Read(0) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(1) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(2) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(3) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(4) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(5) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(6) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(7) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(8) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(9) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(10) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(11) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(12) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(13) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(14) -radix sfixed} {/turbo_tb/TurboDecTop/PCIA_Read(15) -radix sfixed}} -subitemconfig {/turbo_tb/TurboDecTop/PCIA_Read(0) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(3) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(4) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(5) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(6) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(7) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(8) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(9) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(10) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(11) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(12) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(13) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(14) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIA_Read(15) {-height 15 -radix sfixed}} /turbo_tb/TurboDecTop/PCIA_Read
add wave -noupdate -radix sfixed -childformat {{/turbo_tb/TurboDecTop/PCIB_Read(0) -radix sfixed} {/turbo_tb/TurboDecTop/PCIB_Read(1) -radix sfixed} {/turbo_tb/TurboDecTop/PCIB_Read(2) -radix sfixed} {/turbo_tb/TurboDecTop/PCIB_Read(3) -radix sfixed}} -subitemconfig {/turbo_tb/TurboDecTop/PCIB_Read(0) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIB_Read(1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIB_Read(2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/PCIB_Read(3) {-height 15 -radix sfixed}} /turbo_tb/TurboDecTop/PCIB_Read
add wave -noupdate /turbo_tb/TurboDecTop/uHat
add wave -noupdate /turbo_tb/SyncOut
add wave -noupdate -divider {Sova Controls}
add wave -noupdate -radix unsigned /turbo_tb/TurboDecTop/SovaIndex
add wave -noupdate /turbo_tb/TurboDecTop/SovaActiveA
add wave -noupdate /turbo_tb/TurboDecTop/SovaActiveB
add wave -noupdate /turbo_tb/TurboDecTop/SovaReadyA
add wave -noupdate /turbo_tb/TurboDecTop/SovaReadyB
add wave -noupdate /turbo_tb/TurboDecTop/SovaReady
add wave -noupdate /turbo_tb/TurboDecTop/SovaValidOutA
add wave -noupdate /turbo_tb/TurboDecTop/SovaValidOutB
add wave -noupdate -radix unsigned /turbo_tb/OutCntr
add wave -noupdate -radix unsigned -radixshowbase 0 /turbo_tb/BerCount
add wave -noupdate -radix unsigned -radixshowbase 0 /turbo_tb/BerCntr
add wave -noupdate -format Analog-Step -height 74 -max 645412.0 -min 8.0 -radix sfixed -childformat {{/turbo_tb/Magnitude(8) -radix sfixed} {/turbo_tb/Magnitude(7) -radix sfixed} {/turbo_tb/Magnitude(6) -radix sfixed} {/turbo_tb/Magnitude(5) -radix sfixed} {/turbo_tb/Magnitude(4) -radix sfixed} {/turbo_tb/Magnitude(3) -radix sfixed} {/turbo_tb/Magnitude(2) -radix sfixed} {/turbo_tb/Magnitude(1) -radix sfixed} {/turbo_tb/Magnitude(0) -radix sfixed} {/turbo_tb/Magnitude(-1) -radix sfixed} {/turbo_tb/Magnitude(-2) -radix sfixed} {/turbo_tb/Magnitude(-3) -radix sfixed} {/turbo_tb/Magnitude(-4) -radix sfixed} {/turbo_tb/Magnitude(-5) -radix sfixed} {/turbo_tb/Magnitude(-6) -radix sfixed} {/turbo_tb/Magnitude(-7) -radix sfixed} {/turbo_tb/Magnitude(-8) -radix sfixed} {/turbo_tb/Magnitude(-9) -radix sfixed} {/turbo_tb/Magnitude(-10) -radix sfixed} {/turbo_tb/Magnitude(-11) -radix sfixed} {/turbo_tb/Magnitude(-12) -radix sfixed}} -subitemconfig {/turbo_tb/Magnitude(8) {-height 15 -radix sfixed} /turbo_tb/Magnitude(7) {-height 15 -radix sfixed} /turbo_tb/Magnitude(6) {-height 15 -radix sfixed} /turbo_tb/Magnitude(5) {-height 15 -radix sfixed} /turbo_tb/Magnitude(4) {-height 15 -radix sfixed} /turbo_tb/Magnitude(3) {-height 15 -radix sfixed} /turbo_tb/Magnitude(2) {-height 15 -radix sfixed} /turbo_tb/Magnitude(1) {-height 15 -radix sfixed} /turbo_tb/Magnitude(0) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-1) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-2) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-3) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-4) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-5) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-6) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-7) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-8) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-9) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-10) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-11) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-12) {-height 15 -radix sfixed}} /turbo_tb/Magnitude
add wave -noupdate -radix sfixed -childformat {{/turbo_tb/Magnitude(8) -radix sfixed} {/turbo_tb/Magnitude(7) -radix sfixed} {/turbo_tb/Magnitude(6) -radix sfixed} {/turbo_tb/Magnitude(5) -radix sfixed} {/turbo_tb/Magnitude(4) -radix sfixed} {/turbo_tb/Magnitude(3) -radix sfixed} {/turbo_tb/Magnitude(2) -radix sfixed} {/turbo_tb/Magnitude(1) -radix sfixed} {/turbo_tb/Magnitude(0) -radix sfixed} {/turbo_tb/Magnitude(-1) -radix sfixed} {/turbo_tb/Magnitude(-2) -radix sfixed} {/turbo_tb/Magnitude(-3) -radix sfixed} {/turbo_tb/Magnitude(-4) -radix sfixed} {/turbo_tb/Magnitude(-5) -radix sfixed} {/turbo_tb/Magnitude(-6) -radix sfixed} {/turbo_tb/Magnitude(-7) -radix sfixed} {/turbo_tb/Magnitude(-8) -radix sfixed} {/turbo_tb/Magnitude(-9) -radix sfixed} {/turbo_tb/Magnitude(-10) -radix sfixed} {/turbo_tb/Magnitude(-11) -radix sfixed} {/turbo_tb/Magnitude(-12) -radix sfixed}} -subitemconfig {/turbo_tb/Magnitude(8) {-height 15 -radix sfixed} /turbo_tb/Magnitude(7) {-height 15 -radix sfixed} /turbo_tb/Magnitude(6) {-height 15 -radix sfixed} /turbo_tb/Magnitude(5) {-height 15 -radix sfixed} /turbo_tb/Magnitude(4) {-height 15 -radix sfixed} /turbo_tb/Magnitude(3) {-height 15 -radix sfixed} /turbo_tb/Magnitude(2) {-height 15 -radix sfixed} /turbo_tb/Magnitude(1) {-height 15 -radix sfixed} /turbo_tb/Magnitude(0) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-1) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-2) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-3) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-4) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-5) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-6) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-7) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-8) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-9) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-10) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-11) {-height 15 -radix sfixed} /turbo_tb/Magnitude(-12) {-height 15 -radix sfixed}} /turbo_tb/Magnitude
add wave -noupdate -radix sfixed /turbo_tb/DataOut
add wave -noupdate /turbo_tb/uHat
add wave -noupdate /turbo_tb/uHatExpected
add wave -noupdate -radix sfixed -childformat {{/turbo_tb/TurboDecTop/Sova/EuI(7) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(6) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(5) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(4) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(3) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(2) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(1) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(0) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-1) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-2) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-3) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-4) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-5) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-6) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-7) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-8) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-9) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-10) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-11) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/EuI(-12) -radix sfixed}} -subitemconfig {/turbo_tb/TurboDecTop/Sova/EuI(7) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(6) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(5) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(4) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(3) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(0) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-3) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-4) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-5) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-6) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-7) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-8) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-9) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-10) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-11) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/EuI(-12) {-height 15 -radix sfixed}} /turbo_tb/TurboDecTop/Sova/EuI
add wave -noupdate -radix sfixed /turbo_tb/TurboDecTop/Sova/EuO
add wave -noupdate /turbo_tb/Frame
add wave -noupdate /turbo_tb/Rate
add wave -noupdate /turbo_tb/ValidOut
add wave -noupdate -format Analog-Step -height 74 -max 434201.0 -radix sfixed /turbo_tb/TurboDecTop/Sova/MaxMax
add wave -noupdate -radix sfixed /turbo_tb/TurboDecTop/Sova/MinMin
add wave -noupdate /turbo_tb/TurboDecTop/Sova/t
add wave -noupdate -radix sfixed -childformat {{/turbo_tb/TurboDecTop/Sova/pAM(0) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(1) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(2) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(3) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(4) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(5) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(6) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(7) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(8) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(9) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(10) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(11) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(12) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(13) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(14) -radix sfixed} {/turbo_tb/TurboDecTop/Sova/pAM(15) -radix sfixed}} -subitemconfig {/turbo_tb/TurboDecTop/Sova/pAM(0) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(3) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(4) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(5) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(6) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(7) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(8) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(9) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(10) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(11) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(12) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(13) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(14) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/Sova/pAM(15) {-height 15 -radix sfixed}} /turbo_tb/TurboDecTop/Sova/pAM
add wave -noupdate /turbo_tb/TurboDecTop/Sova/Mode
add wave -noupdate /turbo_tb/TurboDecTop/Sova/pAM
add wave -noupdate -format Analog-Step -height 74 -max 269697.0 -min -274222.0 -radix sfixed -childformat {{/turbo_tb/TurboDecTop/FrontEnd/DfI(7) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(6) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(5) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(4) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(3) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(2) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(1) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(0) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-1) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-2) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-3) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-4) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-5) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-6) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-7) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-8) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-9) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-10) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-11) -radix sfixed} {/turbo_tb/TurboDecTop/FrontEnd/DfI(-12) -radix sfixed}} -subitemconfig {/turbo_tb/TurboDecTop/FrontEnd/DfI(7) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(6) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(5) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(4) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(3) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(0) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-1) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-2) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-3) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-4) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-5) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-6) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-7) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-8) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-9) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-10) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-11) {-height 15 -radix sfixed} /turbo_tb/TurboDecTop/FrontEnd/DfI(-12) {-height 15 -radix sfixed}} /turbo_tb/TurboDecTop/FrontEnd/DfI
add wave -noupdate -format Analog-Step -height 74 -max 288892.0 -min -286214.0 -radix sfixed /turbo_tb/TurboDecTop/FrontEnd/DfQ
add wave -noupdate /turbo_tb/TurboDecTop/FrontEnd/SyncIn
add wave -noupdate /turbo_tb/TurboDecTop/FrontEnd/ValidIn
add wave -noupdate -radix unsigned /turbo_tb/SymCntr
add wave -noupdate /turbo_tb/ValidData
add wave -noupdate -format Analog-Step -height 74 -max 23820.0 -min -23428.0 -radix sfixed /turbo_tb/DataI
add wave -noupdate -format Analog-Step -height 74 -max 25026.000000000004 -min -27451.0 -radix sfixed /turbo_tb/DataQ
add wave -noupdate -format Analog-Step -height 74 -max 31640.0 -min -33224.0 -radix sfixed /turbo_tb/NoiseI
add wave -noupdate -format Analog-Step -height 74 -max 29208.999999999996 -min -30250.0 -radix sfixed /turbo_tb/NoiseQ
add wave -noupdate -format Analog-Step -height 74 -max 32997.0 -min -37314.0 -radix sfixed /turbo_tb/SumI
add wave -noupdate -format Analog-Step -height 74 -max 34914.000000000007 -min -35036.0 -radix sfixed /turbo_tb/SumQ
add wave -noupdate /turbo_tb/Gain
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5788528000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 248
configure wave -valuecolwidth 146
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {4935402880 ps} {6641653120 ps}
