# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/modem/vivado/xc7k160t-IP/invSinc/invSinc.xci
# IP: The module: 'invSinc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/modem/vivado/xc7k160t-IP/invSinc/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'invSinc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/modem/vivado/xc7k160t-IP/invSinc/invSinc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'invSinc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/modem/vivado/xc7k160t-IP/invSinc/invSinc.xci
# IP: The module: 'invSinc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/modem/vivado/xc7k160t-IP/invSinc/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'invSinc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/modem/vivado/xc7k160t-IP/invSinc/invSinc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'invSinc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
