onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix sfixed /cmplphsdettb/I1Noisy
add wave -noupdate -radix sfixed /cmplphsdettb/I2Noisy
add wave -noupdate -radix sfixed /cmplphsdettb/Q1Noisy
add wave -noupdate -radix sfixed /cmplphsdettb/Q2Noisy
add wave -noupdate /cmplphsdettb/Real1Out
add wave -noupdate /cmplphsdettb/Imag1Out
add wave -noupdate /cmplphsdettb/AlignIFs/Delay_u/Diff
add wave -noupdate /cmplphsdettb/AlignIFs/Delay_u/RdOutA
add wave -noupdate /cmplphsdettb/AlignIFs/Delay_u/RdOutB
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/d
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/s_axis_a_tdata
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/\\reg_array\[17\].fde_used.u2\\
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/reset
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/decay
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/attack
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/\\op_mem_22_20_reg\[0\]\\
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/mult6_p_net
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/mult6_p_net_x0
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/mult7_p_net
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/mult7_p_net_x0
add wave -noupdate /cmplphsdettb/AlignIFs/ValidOut
add wave -noupdate /cmplphsdettb/AlignIFs/ValidOverAdd
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/fast_agc1/q
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/fast_agc1/\\inferred_dsp.reg_mult.m_reg_reg\\
add wave -noupdate /cmplphsdettb/CmplxPhsDet/U0/complexphasedetector_struct/agcchanswapper/fast_agc1/reset
add wave -noupdate /cmplphsdettb/CmplxPhsDet/agc1_gt_agc2
add wave -noupdate /cmplphsdettb/CmplxPhsDet/realxord
add wave -noupdate /cmplphsdettb/CmplxPhsDet/locked_n
add wave -noupdate /cmplphsdettb/CmplxPhsDet/reallock
add wave -noupdate /cmplphsdettb/CmplxPhsDet/realout
add wave -noupdate /cmplphsdettb/dac0_d
add wave -noupdate /cmplphsdettb/dac1_d
add wave -noupdate /cmplphsdettb/lockLed0n
add wave -noupdate /cmplphsdettb/lockLed1n
add wave -noupdate /cmplphsdettb/ch3ClkOut
add wave -noupdate /cmplphsdettb/ch3DataOut
add wave -noupdate /cmplphsdettb/AlignIFs/ValidAbs
add wave -noupdate -format Analog-Step -height 74 -max 102168.0 -radix ufixed -childformat {{/cmplphsdettb/AlignIFs/AbsCntr(4) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(3) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(2) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(1) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(0) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-1) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-2) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-3) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-4) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-5) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-6) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-7) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-8) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-9) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-10) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-11) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-12) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-13) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-14) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsCntr(-15) -radix ufixed}} -subitemconfig {/cmplphsdettb/AlignIFs/AbsCntr(4) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(3) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(2) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(1) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(0) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-1) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-2) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-3) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-4) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-5) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-6) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-7) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-8) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-9) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-10) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-11) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-12) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-13) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-14) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsCntr(-15) {-height 15 -radix ufixed}} /cmplphsdettb/AlignIFs/AbsCntr
add wave -noupdate -format Analog-Step -height 74 -max 102168.0 -radix ufixed -childformat {{/cmplphsdettb/AlignIFs/MaxCntr(4) -radix ufixed} {/cmplphsdettb/AlignIFs/MaxCntr(3) -radix ufixed} {/cmplphsdettb/AlignIFs/MaxCntr(2) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(1) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(0) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-1) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-2) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-3) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-4) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-5) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-6) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-7) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-8) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-9) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-10) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-11) -radix sfixed} {/cmplphsdettb/AlignIFs/MaxCntr(-12) -radix ufixed} {/cmplphsdettb/AlignIFs/MaxCntr(-13) -radix ufixed} {/cmplphsdettb/AlignIFs/MaxCntr(-14) -radix ufixed} {/cmplphsdettb/AlignIFs/MaxCntr(-15) -radix ufixed}} -subitemconfig {/cmplphsdettb/AlignIFs/MaxCntr(4) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/MaxCntr(3) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/MaxCntr(2) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(1) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(0) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-1) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-2) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-3) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-4) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-5) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-6) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-7) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-8) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-9) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-10) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-11) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/MaxCntr(-12) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/MaxCntr(-13) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/MaxCntr(-14) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/MaxCntr(-15) {-height 15 -radix ufixed}} /cmplphsdettb/AlignIFs/MaxCntr
add wave -noupdate -format Analog-Step -height 74 -max 102168.0 -radix ufixed -childformat {{/cmplphsdettb/AlignIFs/AbsPeak(4) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsPeak(3) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsPeak(2) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(1) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(0) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-1) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-2) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-3) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-4) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-5) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-6) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-7) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-8) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-9) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-10) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-11) -radix sfixed} {/cmplphsdettb/AlignIFs/AbsPeak(-12) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsPeak(-13) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsPeak(-14) -radix ufixed} {/cmplphsdettb/AlignIFs/AbsPeak(-15) -radix ufixed}} -subitemconfig {/cmplphsdettb/AlignIFs/AbsPeak(4) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsPeak(3) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsPeak(2) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(1) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(0) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-1) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-2) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-3) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-4) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-5) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-6) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-7) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-8) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-9) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-10) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-11) {-height 15 -radix sfixed} /cmplphsdettb/AlignIFs/AbsPeak(-12) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsPeak(-13) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsPeak(-14) {-height 15 -radix ufixed} /cmplphsdettb/AlignIFs/AbsPeak(-15) {-height 15 -radix ufixed}} /cmplphsdettb/AlignIFs/AbsPeak
add wave -noupdate -radix unsigned -radixshowbase 0 /cmplphsdettb/AlignIFs/AbsIndex
add wave -noupdate -radix unsigned -radixshowbase 0 /cmplphsdettb/AlignIFs/Index0
add wave -noupdate -format Analog-Step -height 74 -max 56.0 -radix unsigned /cmplphsdettb/AlignIFs/IndexOut
add wave -noupdate /cmplphsdettb/AlignIFs/AbeforeB
add wave -noupdate -radix unsigned /cmplphsdettb/Delay
add wave -noupdate -format Analog-Step -height 74 -max 127.0 -radix hexadecimal /cmplphsdettb/AlignIFs/IndexAbs
add wave -noupdate -radix hexadecimal /cmplphsdettb/AlignIFs/IndexAcc
add wave -noupdate -radix decimal /cmplphsdettb/AlignIFs/SkipFirst2
add wave -noupdate -format Analog-Step -height 74 -max 67813.999999999985 -min -46446.0 -radix sfixed -childformat {{/cmplphsdettb/Filtered1Noise(2) -radix sfixed} {/cmplphsdettb/Filtered1Noise(1) -radix sfixed} {/cmplphsdettb/Filtered1Noise(0) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-1) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-2) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-3) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-4) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-5) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-6) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-7) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-8) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-9) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-10) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-11) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-12) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-13) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-14) -radix sfixed} {/cmplphsdettb/Filtered1Noise(-15) -radix sfixed}} -subitemconfig {/cmplphsdettb/Filtered1Noise(2) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(1) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(0) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-1) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-2) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-3) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-4) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-5) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-6) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-7) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-8) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-9) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-10) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-11) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-12) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-13) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-14) {-height 15 -radix sfixed} /cmplphsdettb/Filtered1Noise(-15) {-height 15 -radix sfixed}} /cmplphsdettb/Filtered1Noise
add wave -noupdate -format Analog-Step -height 74 -max 43310.000000000007 -min -52933.0 -radix sfixed -childformat {{/cmplphsdettb/Filtered2Noise(2) -radix sfixed} {/cmplphsdettb/Filtered2Noise(1) -radix sfixed} {/cmplphsdettb/Filtered2Noise(0) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-1) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-2) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-3) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-4) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-5) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-6) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-7) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-8) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-9) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-10) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-11) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-12) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-13) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-14) -radix sfixed} {/cmplphsdettb/Filtered2Noise(-15) -radix sfixed}} -subitemconfig {/cmplphsdettb/Filtered2Noise(2) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(1) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(0) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-1) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-2) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-3) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-4) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-5) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-6) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-7) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-8) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-9) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-10) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-11) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-12) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-13) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-14) {-height 15 -radix sfixed} /cmplphsdettb/Filtered2Noise(-15) {-height 15 -radix sfixed}} /cmplphsdettb/Filtered2Noise
add wave -noupdate -format Analog-Step -height 74 -max 21665.0 -radix sfixed -childformat {{/cmplphsdettb/Noise2Rms(0) -radix sfixed} {/cmplphsdettb/Noise2Rms(-1) -radix sfixed} {/cmplphsdettb/Noise2Rms(-2) -radix sfixed} {/cmplphsdettb/Noise2Rms(-3) -radix sfixed} {/cmplphsdettb/Noise2Rms(-4) -radix sfixed} {/cmplphsdettb/Noise2Rms(-5) -radix sfixed} {/cmplphsdettb/Noise2Rms(-6) -radix sfixed} {/cmplphsdettb/Noise2Rms(-7) -radix sfixed} {/cmplphsdettb/Noise2Rms(-8) -radix sfixed} {/cmplphsdettb/Noise2Rms(-9) -radix sfixed} {/cmplphsdettb/Noise2Rms(-10) -radix sfixed} {/cmplphsdettb/Noise2Rms(-11) -radix sfixed} {/cmplphsdettb/Noise2Rms(-12) -radix sfixed} {/cmplphsdettb/Noise2Rms(-13) -radix sfixed} {/cmplphsdettb/Noise2Rms(-14) -radix sfixed} {/cmplphsdettb/Noise2Rms(-15) -radix sfixed} {/cmplphsdettb/Noise2Rms(-16) -radix sfixed} {/cmplphsdettb/Noise2Rms(-17) -radix sfixed}} -subitemconfig {/cmplphsdettb/Noise2Rms(0) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-1) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-2) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-3) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-4) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-5) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-6) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-7) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-8) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-9) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-10) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-11) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-12) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-13) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-14) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-15) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-16) {-height 15 -radix sfixed} /cmplphsdettb/Noise2Rms(-17) {-height 15 -radix sfixed}} /cmplphsdettb/Noise2Rms
add wave -noupdate -format Analog-Step -height 74 -max 45794.0 -radix sfixed /cmplphsdettb/I1Rms
add wave -noupdate -format Analog-Step -height 74 -max 131071.00000000001 -min -131072.0 -radix sfixed -childformat {{/cmplphsdettb/Noise1Gained(1) -radix sfixed} {/cmplphsdettb/Noise1Gained(0) -radix sfixed} {/cmplphsdettb/Noise1Gained(-1) -radix sfixed} {/cmplphsdettb/Noise1Gained(-2) -radix sfixed} {/cmplphsdettb/Noise1Gained(-3) -radix sfixed} {/cmplphsdettb/Noise1Gained(-4) -radix sfixed} {/cmplphsdettb/Noise1Gained(-5) -radix sfixed} {/cmplphsdettb/Noise1Gained(-6) -radix sfixed} {/cmplphsdettb/Noise1Gained(-7) -radix sfixed} {/cmplphsdettb/Noise1Gained(-8) -radix sfixed} {/cmplphsdettb/Noise1Gained(-9) -radix sfixed} {/cmplphsdettb/Noise1Gained(-10) -radix sfixed} {/cmplphsdettb/Noise1Gained(-11) -radix sfixed} {/cmplphsdettb/Noise1Gained(-12) -radix sfixed} {/cmplphsdettb/Noise1Gained(-13) -radix sfixed} {/cmplphsdettb/Noise1Gained(-14) -radix sfixed} {/cmplphsdettb/Noise1Gained(-15) -radix sfixed} {/cmplphsdettb/Noise1Gained(-16) -radix sfixed}} -subitemconfig {/cmplphsdettb/Noise1Gained(1) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(0) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-1) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-2) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-3) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-4) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-5) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-6) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-7) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-8) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-9) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-10) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-11) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-12) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-13) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-14) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-15) {-height 15 -radix sfixed} /cmplphsdettb/Noise1Gained(-16) {-height 15 -radix sfixed}} /cmplphsdettb/Noise1Gained
add wave -noupdate -format Analog-Step -height 74 -max 131071.00000000001 -min -131072.0 -radix sfixed /cmplphsdettb/Noise2Gained
add wave -noupdate -format Analog-Step -height 74 -max 92668.0 -min -92668.0 -radix sfixed -childformat {{/cmplphsdettb/DataI(0) -radix sfixed} {/cmplphsdettb/DataI(-1) -radix sfixed} {/cmplphsdettb/DataI(-2) -radix sfixed} {/cmplphsdettb/DataI(-3) -radix sfixed} {/cmplphsdettb/DataI(-4) -radix sfixed} {/cmplphsdettb/DataI(-5) -radix sfixed} {/cmplphsdettb/DataI(-6) -radix sfixed} {/cmplphsdettb/DataI(-7) -radix sfixed} {/cmplphsdettb/DataI(-8) -radix sfixed} {/cmplphsdettb/DataI(-9) -radix sfixed} {/cmplphsdettb/DataI(-10) -radix sfixed} {/cmplphsdettb/DataI(-11) -radix sfixed} {/cmplphsdettb/DataI(-12) -radix sfixed} {/cmplphsdettb/DataI(-13) -radix sfixed} {/cmplphsdettb/DataI(-14) -radix sfixed} {/cmplphsdettb/DataI(-15) -radix sfixed} {/cmplphsdettb/DataI(-16) -radix sfixed} {/cmplphsdettb/DataI(-17) -radix sfixed}} -subitemconfig {/cmplphsdettb/DataI(0) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-1) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-2) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-3) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-4) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-5) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-6) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-7) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-8) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-9) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-10) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-11) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-12) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-13) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-14) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-15) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-16) {-height 15 -radix sfixed} /cmplphsdettb/DataI(-17) {-height 15 -radix sfixed}} /cmplphsdettb/DataI
add wave -noupdate -format Analog-Step -height 74 -max 57256.0 -min -57257.0 -radix sfixed -childformat {{/cmplphsdettb/FilteredI(1) -radix hexadecimal} {/cmplphsdettb/FilteredI(0) -radix sfixed} {/cmplphsdettb/FilteredI(-1) -radix sfixed} {/cmplphsdettb/FilteredI(-2) -radix sfixed} {/cmplphsdettb/FilteredI(-3) -radix sfixed} {/cmplphsdettb/FilteredI(-4) -radix sfixed} {/cmplphsdettb/FilteredI(-5) -radix sfixed} {/cmplphsdettb/FilteredI(-6) -radix sfixed} {/cmplphsdettb/FilteredI(-7) -radix sfixed} {/cmplphsdettb/FilteredI(-8) -radix sfixed} {/cmplphsdettb/FilteredI(-9) -radix sfixed} {/cmplphsdettb/FilteredI(-10) -radix sfixed} {/cmplphsdettb/FilteredI(-11) -radix sfixed} {/cmplphsdettb/FilteredI(-12) -radix sfixed} {/cmplphsdettb/FilteredI(-13) -radix sfixed} {/cmplphsdettb/FilteredI(-14) -radix sfixed} {/cmplphsdettb/FilteredI(-15) -radix sfixed} {/cmplphsdettb/FilteredI(-16) -radix sfixed}} -subitemconfig {/cmplphsdettb/FilteredI(1) {-height 15 -radix hexadecimal} /cmplphsdettb/FilteredI(0) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-1) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-2) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-3) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-4) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-5) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-6) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-7) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-8) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-9) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-10) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-11) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-12) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-13) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-14) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-15) {-height 15 -radix sfixed} /cmplphsdettb/FilteredI(-16) {-height 15 -radix sfixed}} /cmplphsdettb/FilteredI
add wave -noupdate -radix sfixed /cmplphsdettb/DataQ
add wave -noupdate -radix sfixed /cmplphsdettb/FilteredQ
add wave -noupdate /cmplphsdettb/AlignIFs/PackFifo/Restart
add wave -noupdate /cmplphsdettb/AlignIFs/PackFifo/WrEn
add wave -noupdate /cmplphsdettb/AlignIFs/PackFifo/RdCount
add wave -noupdate /cmplphsdettb/BitCounter
add wave -noupdate /cmplphsdettb/NoiseGain1
add wave -noupdate /cmplphsdettb/NoiseGain2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {9824809000 ps} 0} {{Cursor 2} {400293 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 345
configure wave -valuecolwidth 114
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {5250 ns}
bookmark add wave bookmark0 {{2508730 ps} {2540670 ps}} 0
bookmark add wave bookmark1 {{3023030 ps} {3054970 ps}} 0
bookmark add wave bookmark2 {{2187685 ps} {2199857 ps}} 33
bookmark add wave bookmark3 {{3212803 ps} {3228773 ps}} 48
