webtalk_init -webtalk_dir C:/modem/vivado/semcoDemod.sim/simMultih/synth/func/xsim.dir/test_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 10 14:19:41 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1733598" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210680342_206273022_210624955_246" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1e6ee2c9-36f0-46c1-999b-645ad345689f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0027b497f38f46a7b40b8158d1351c26" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4340100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "31" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "54.77_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "721064_KB" -context "xsim\\usage"
webtalk_transmit -clientid 270840141 -regid "210680342_206273022_210624955_246" -xml C:/modem/vivado/semcoDemod.sim/simMultih/synth/func/xsim.dir/test_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/modem/vivado/semcoDemod.sim/simMultih/synth/func/xsim.dir/test_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/modem/vivado/semcoDemod.sim/simMultih/synth/func/xsim.dir/test_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
