#!/bin/bash -f
# Vivado (TM) v2016.3 (64-bit)
#
# Filename    : design_2.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Oct 10 09:03:06 -0400 2019
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016 
#
# usage: design_2.sh [-help]
# usage: design_2.sh [-lib_map_path]
# usage: design_2.sh [-noclean_files]
# usage: design_2.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_2.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm blk_mem_gen_v8_3_4 xbip_utils_v3_0_7 c_reg_fd_v12_0_3 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_3 xbip_dsp48_addsub_v3_0_3 xbip_addsub_v3_0_3 c_addsub_v12_0_10 util_vector_logic_v2_0)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "design_2.sh - Script generated by export_simulation (Vivado v2016.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog \
    "C:/Xilinx/Vivado/2016.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2016.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/calc_ma.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/calc_n.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/calc_n_12.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/calc_n_23.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScal3i2.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScal8jQ.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScalbvn.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScalcGz.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScaldAI.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScaldeE.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScaldiF.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScaldjF.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/HLSLdpcLogDecScaledMin.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/load_pest_12_bot.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/load_pest_12_top.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/load_pest_all.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/load_pest_all_23.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxbkb.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxcud.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxdEe.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxeOg.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxfYi.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxg8j.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxhbi.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxibs.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxjbC.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_12_varinxkbM.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxAem.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxBew.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxCeG.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxlbW.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxmb6.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxncg.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxocq.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxpcA.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxqcK.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxrcU.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxsc4.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxtde.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxudo.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxvdy.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxwdI.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxxdS.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxyd2.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_23_varinxzec.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AEe0.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AFfa.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AGfk.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AHfu.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AIfE.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AJfO.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18ARg6.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AShg.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AThq.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AUhA.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AVhK.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18AWhU.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18B0iy.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18B1iI.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18B2iS.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BKfY.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BLf8.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BMgi.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BNgs.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BOgC.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BPgM.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BXh4.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BYie.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx18BZio.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx3_1DeQ.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcAA_varinx3_4QgW.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcB.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcC.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcD.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcE.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcF.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/mcalcG.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/setup_calc.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/setup_calc_12.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/setup_calc_23.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/update_hat_all.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/update_lam_all.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/update_lam_all_12.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/update_lam_all_23.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/write_result.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/write_result_12.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/32b0/hdl/verilog/write_result_23.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_HLSLdpcLogDecScaledMin_0_0/sim/design_2_HLSLdpcLogDecScaledMin_0_0.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/ecf4/hdl/verilog/setupLDPC.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_setupLDPC_0_0/sim/design_2_setupLDPC_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_4 $vlogan_opts +v2k \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/59b0/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_blk_mem_gen_0_3/sim/design_2_blk_mem_gen_0_3.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_0_0/sim/design_2_raw_data_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_blk_mem_gen_0_4/sim/design_2_blk_mem_gen_0_4.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_0_0/sim/design_2_decode_data_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_7 $vhdlan_opts \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/6fc3/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_3 $vhdlan_opts \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/e1e2/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/1e87/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/7db8/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/c9c4/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/2957/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_10 $vhdlan_opts \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/a394/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux_0/sim/design_2_data_mux_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/ipshared/0673/hdl/verilog/LDPC_CTRL.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_LDPC_CTRL_0_0/sim/design_2_LDPC_CTRL_0_0.v" \
    "$ref_dir/../../../bd/design_2/ipshared/e147/xlconstant.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconstant_0_0/sim/design_2_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work util_vector_logic_v2_0 $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ipshared/1d19/hdl/util_vector_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_vector_logic_0_0/sim/design_2_util_vector_logic_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_0/sim/design_2_data_ce_mux_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_1/sim/design_2_data_ce_mux_1.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_2/sim/design_2_data_ce_mux_2.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux2_0/sim/design_2_raw_ce_mux2_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_vector_logic_0_1/sim/design_2_util_vector_logic_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconstant_1_0/sim/design_2_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/design_2/hdl/design_2.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconstant_2_0/sim/design_2_xlconstant_2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_0_1/sim/design_2_c_addsub_0_1.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_0_2/sim/design_2_c_addsub_0_2.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_2_0/sim/design_2_c_addsub_2_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_3_0/sim/design_2_c_addsub_3_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_3_1/sim/design_2_c_addsub_3_1.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_4_0/sim/design_2_c_addsub_4_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_5_0/sim/design_2_c_addsub_5_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_6_0/sim/design_2_c_addsub_6_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_0_0/sim/design_2_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_8_0/sim/design_2_c_addsub_8_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_c_addsub_8_1/sim/design_2_c_addsub_8_1.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_mux_lat_0/sim/design_2_mux_lat_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_buff_start_lat_0/sim/design_2_buff_start_lat_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_mux_lat_1/sim/design_2_mux_lat_1.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_start_lat_0/sim/design_2_decode_start_lat_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/a227/hdl/verilog/LDPC_Out.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_LDPC_Out_0_0/sim/design_2_LDPC_Out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_mux_lat_2/sim/design_2_mux_lat_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/0a8b/hdl/verilog/LDPC_buff.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/0a8b/hdl/verilog/write_raw_data.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_LDPC_buff_0_0/sim/design_2_LDPC_buff_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a_0/sim/design_2_raw_data_a_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b_0/sim/design_2_raw_data_b_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa_1/sim/design_2_raw_ce_mux_aa_1.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba_1/sim/design_2_raw_ce_mux_ba_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a1_0/sim/design_2_raw_data_a1_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b1_0/sim/design_2_raw_data_b1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa1_0/sim/design_2_raw_ce_mux_aa1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba1_0/sim/design_2_raw_ce_mux_ba1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a2_0/sim/design_2_raw_data_a2_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b2_0/sim/design_2_raw_data_b2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa2_0/sim/design_2_raw_ce_mux_aa2_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba2_0/sim/design_2_raw_ce_mux_ba2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a3_0/sim/design_2_raw_data_a3_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b3_0/sim/design_2_raw_data_b3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa3_0/sim/design_2_raw_ce_mux_aa3_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba3_0/sim/design_2_raw_ce_mux_ba3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a4_0/sim/design_2_raw_data_a4_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b4_0/sim/design_2_raw_data_b4_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa4_0/sim/design_2_raw_ce_mux_aa4_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba4_0/sim/design_2_raw_ce_mux_ba4_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a5_0/sim/design_2_raw_data_a5_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b5_0/sim/design_2_raw_data_b5_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa5_0/sim/design_2_raw_ce_mux_aa5_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba5_0/sim/design_2_raw_ce_mux_ba5_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a6_0/sim/design_2_raw_data_a6_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b6_0/sim/design_2_raw_data_b6_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa6_0/sim/design_2_raw_ce_mux_aa6_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba6_0/sim/design_2_raw_ce_mux_ba6_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a7_0/sim/design_2_raw_data_a7_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b7_0/sim/design_2_raw_data_b7_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa7_0/sim/design_2_raw_ce_mux_aa7_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba7_0/sim/design_2_raw_ce_mux_ba7_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_a8_0/sim/design_2_raw_data_a8_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_data_b8_0/sim/design_2_raw_data_b8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_aa8_0/sim/design_2_raw_ce_mux_aa8_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_raw_ce_mux_ba8_0/sim/design_2_raw_ce_mux_ba8_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconstant_0_1/sim/design_2_xlconstant_0_1.v" \
    "$ref_dir/../../../../ldpc_dual.srcs/sources_1/bd/design_2/ipshared/4430/hdl/verilog/LDPC_Div.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_LDPC_Div_0_0/sim/design_2_LDPC_Div_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_a_0_0/sim/design_2_decode_data_a_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_b_0_0/sim/design_2_decode_data_b_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_3/sim/design_2_data_ce_mux_3.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux1_0/sim/design_2_data_ce_mux1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux1_0/sim/design_2_data_mux1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_b_1_0/sim/design_2_decode_data_b_1_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_a_1_0/sim/design_2_decode_data_a_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_bb_1_0/sim/design_2_data_ce_mux_bb_1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_ab_1_0/sim/design_2_data_ce_mux_ab_1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux11_0/sim/design_2_data_mux11_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_b_2_0/sim/design_2_decode_data_b_2_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_a_2_0/sim/design_2_decode_data_a_2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_bb_2_0/sim/design_2_data_ce_mux_bb_2_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_ab_2_0/sim/design_2_data_ce_mux_ab_2_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux12_0/sim/design_2_data_mux12_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_b_3_0/sim/design_2_decode_data_b_3_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_a_3_0/sim/design_2_decode_data_a_3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_bb_3_0/sim/design_2_data_ce_mux_bb_3_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_ab_3_0/sim/design_2_data_ce_mux_ab_3_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux13_0/sim/design_2_data_mux13_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_b_4_0/sim/design_2_decode_data_b_4_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_a_4_0/sim/design_2_decode_data_a_4_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux14_0/sim/design_2_data_mux14_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_bb_4_0/sim/design_2_data_ce_mux_bb_4_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_ab_4_0/sim/design_2_data_ce_mux_ab_4_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_b_5_0/sim/design_2_decode_data_b_5_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_a_5_0/sim/design_2_decode_data_a_5_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_bb_5_0/sim/design_2_data_ce_mux_bb_5_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_ab_5_0/sim/design_2_data_ce_mux_ab_5_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux15_0/sim/design_2_data_mux15_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_b_6_0/sim/design_2_decode_data_b_6_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_data_a_6_0/sim/design_2_decode_data_a_6_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_mux16_0/sim/design_2_data_mux16_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_bb_6_0/sim/design_2_data_ce_mux_bb_6_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_data_ce_mux_ab_6_0/sim/design_2_data_ce_mux_ab_6_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/design_2/ip/design_2_HLSLdpcLogDecScaledMin_0_1/sim/design_2_HLSLdpcLogDecScaledMin_0_1.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconstant_3_0/sim/design_2_xlconstant_3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_itt_num_lat_0/sim/design_2_itt_num_lat_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_decode_start_lat_1/sim/design_2_decode_start_lat_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_2 xil_defaultlib.glbl -o design_2_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_2_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_2.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_2_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_2_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_2.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_2.sh [-help]\n\
Usage: design_2.sh [-lib_map_path]\n\
Usage: design_2.sh [-reset_run]\n\
Usage: design_2.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
