#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("data_out", 1, hls_out, 0, "ap_vld", "out_data", 1),
	Port_Property("data_out_ap_vld", 1, hls_out, 0, "ap_vld", "out_vld", 1),
	Port_Property("reset", 1, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("cur_read_pos_V", 16, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("cur_read_pos_V_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("numbits_V", 16, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("rd_clk_in", 1, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("rd_mux", 1, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("rd_mux_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("mem_out0_address0", 11, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("mem_out0_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out0_q0", 1, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("mem_out1_address0", 11, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("mem_out1_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out1_q0", 1, hls_in, 7, "ap_memory", "mem_dout", 1),
	Port_Property("mem_out2_address0", 10, hls_out, 8, "ap_memory", "mem_address", 1),
	Port_Property("mem_out2_ce0", 1, hls_out, 8, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out2_q0", 1, hls_in, 8, "ap_memory", "mem_dout", 1),
	Port_Property("mem_out3_address0", 10, hls_out, 9, "ap_memory", "mem_address", 1),
	Port_Property("mem_out3_ce0", 1, hls_out, 9, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out3_q0", 1, hls_in, 9, "ap_memory", "mem_dout", 1),
	Port_Property("mem_out4_address0", 10, hls_out, 10, "ap_memory", "mem_address", 1),
	Port_Property("mem_out4_ce0", 1, hls_out, 10, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out4_q0", 1, hls_in, 10, "ap_memory", "mem_dout", 1),
	Port_Property("mem_out5_address0", 10, hls_out, 11, "ap_memory", "mem_address", 1),
	Port_Property("mem_out5_ce0", 1, hls_out, 11, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out5_q0", 1, hls_in, 11, "ap_memory", "mem_dout", 1),
	Port_Property("mem_out6_address0", 10, hls_out, 12, "ap_memory", "mem_address", 1),
	Port_Property("mem_out6_ce0", 1, hls_out, 12, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out6_q0", 1, hls_in, 12, "ap_memory", "mem_dout", 1),
	Port_Property("mem_out7_address0", 10, hls_out, 13, "ap_memory", "mem_address", 1),
	Port_Property("mem_out7_ce0", 1, hls_out, 13, "ap_memory", "mem_ce", 1),
	Port_Property("mem_out7_q0", 1, hls_in, 13, "ap_memory", "mem_dout", 1),
};
const char* HLS_Design_Meta::dut_name = "LDPC_Out";
