#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("size_V", 2, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("rate_V", 2, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("nR_M_V", 16, hls_out, 2, "ap_ovld", "out_data", 1),
	Port_Property("nR_M_V_ap_vld", 1, hls_out, 2, "ap_ovld", "out_vld", 1),
	Port_Property("etaIndexM_M_V", 16, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("etaIndexM_M_V_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("etaIndexN_M_V", 16, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("etaIndexN_M_V_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("pCodeM_V", 16, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("pCodeM_V_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("pMaxIterations_V", 16, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("pMaxIterations_V_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("etaIndexM_V_address0", 16, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("etaIndexM_V_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("etaIndexM_V_we0", 1, hls_out, 7, "ap_memory", "mem_we", 1),
	Port_Property("etaIndexM_V_d0", 16, hls_out, 7, "ap_memory", "mem_din", 1),
	Port_Property("etaIndexN_V_address0", 16, hls_out, 8, "ap_memory", "mem_address", 1),
	Port_Property("etaIndexN_V_ce0", 1, hls_out, 8, "ap_memory", "mem_ce", 1),
	Port_Property("etaIndexN_V_we0", 1, hls_out, 8, "ap_memory", "mem_we", 1),
	Port_Property("etaIndexN_V_d0", 16, hls_out, 8, "ap_memory", "mem_din", 1),
	Port_Property("lambdaIndexM_V_address0", 16, hls_out, 9, "ap_memory", "mem_address", 1),
	Port_Property("lambdaIndexM_V_ce0", 1, hls_out, 9, "ap_memory", "mem_ce", 1),
	Port_Property("lambdaIndexM_V_we0", 1, hls_out, 9, "ap_memory", "mem_we", 1),
	Port_Property("lambdaIndexM_V_d0", 16, hls_out, 9, "ap_memory", "mem_din", 1),
	Port_Property("dout", 1, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("dout_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("din", 1, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("cs", 1, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("cs_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
	Port_Property("clk", 1, hls_out, 13, "ap_vld", "out_data", 1),
	Port_Property("clk_ap_vld", 1, hls_out, 13, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "setupLDPC";
